////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD91G0LM_H_
#define _MSD91G0LM_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PIN_6 PAD_RX2P_B
#define PAD_RX2P_B 221
#define GPIO_PAD_221 GPIO220
#ifndef PIN_6_IS_GPIO
#define PIN_6_IS_GPIO 0
#endif 
#ifndef PAD_RX2P_B_IS_GPIO
#define PAD_RX2P_B_IS_GPIO PIN_6_IS_GPIO
#endif 

#define PIN_10 PAD_RX0N_A
#define PAD_RX0N_A 207
#define GPIO_PAD_207 GPIO206
#ifndef PIN_10_IS_GPIO
#define PIN_10_IS_GPIO 0
#endif 
#ifndef PAD_RX0N_A_IS_GPIO
#define PAD_RX0N_A_IS_GPIO PIN_10_IS_GPIO
#endif 

#define PIN_8 PAD_RXCN_A
#define PAD_RXCN_A 206
#define GPIO_PAD_206 GPIO205
#ifndef PIN_8_IS_GPIO
#define PIN_8_IS_GPIO 0
#endif 
#ifndef PAD_RXCN_A_IS_GPIO
#define PAD_RXCN_A_IS_GPIO PIN_8_IS_GPIO
#endif 

#define PIN_11 PAD_RX0P_A
#define PAD_RX0P_A 211
#define GPIO_PAD_211 GPIO210
#ifndef PIN_11_IS_GPIO
#define PIN_11_IS_GPIO 0
#endif 
#ifndef PAD_RX0P_A_IS_GPIO
#define PAD_RX0P_A_IS_GPIO PIN_11_IS_GPIO
#endif 

#define PIN_9 PAD_RXCP_A
#define PAD_RXCP_A 210
#define GPIO_PAD_210 GPIO209
#ifndef PIN_9_IS_GPIO
#define PIN_9_IS_GPIO 0
#endif 
#ifndef PAD_RXCP_A_IS_GPIO
#define PAD_RXCP_A_IS_GPIO PIN_9_IS_GPIO
#endif 

#define PIN_14 PAD_RX2N_A
#define PAD_RX2N_A 209
#define GPIO_PAD_209 GPIO208
#ifndef PIN_14_IS_GPIO
#define PIN_14_IS_GPIO 0
#endif 
#ifndef PAD_RX2N_A_IS_GPIO
#define PAD_RX2N_A_IS_GPIO PIN_14_IS_GPIO
#endif 

#define PIN_12 PAD_RX1N_A
#define PAD_RX1N_A 208
#define GPIO_PAD_208 GPIO207
#ifndef PIN_12_IS_GPIO
#define PIN_12_IS_GPIO 0
#endif 
#ifndef PAD_RX1N_A_IS_GPIO
#define PAD_RX1N_A_IS_GPIO PIN_12_IS_GPIO
#endif 

#define PIN_15 PAD_RX2P_A
#define PAD_RX2P_A 213
#define GPIO_PAD_213 GPIO212
#ifndef PIN_15_IS_GPIO
#define PIN_15_IS_GPIO 0
#endif 
#ifndef PAD_RX2P_A_IS_GPIO
#define PAD_RX2P_A_IS_GPIO PIN_15_IS_GPIO
#endif 

#define PIN_13 PAD_RX1P_A
#define PAD_RX1P_A 212
#define GPIO_PAD_212 GPIO211
#ifndef PIN_13_IS_GPIO
#define PIN_13_IS_GPIO 0
#endif 
#ifndef PAD_RX1P_A_IS_GPIO
#define PAD_RX1P_A_IS_GPIO PIN_13_IS_GPIO
#endif 

#define PIN_16 PADA_HSYNC0
#define PADA_HSYNC0 172
#define GPIO_PAD_172 GPIO171
#ifndef PIN_16_IS_GPIO
#define PIN_16_IS_GPIO 0
#endif 
#ifndef PADA_HSYNC0_IS_GPIO
#define PADA_HSYNC0_IS_GPIO PIN_16_IS_GPIO
#endif 

#define PIN_17 PADA_BIN0P
#define PADA_BIN0P 190
#define GPIO_PAD_190 GPIO189
#ifndef PIN_17_IS_GPIO
#define PIN_17_IS_GPIO 0
#endif 
#ifndef PADA_BIN0P_IS_GPIO
#define PADA_BIN0P_IS_GPIO PIN_17_IS_GPIO
#endif 

#define PADA_BIN0M 9999
#ifndef PADA_BIN0M_IS_GPIO
#define PADA_BIN0M_IS_GPIO 0
#endif 

#define PIN_18 PADA_GIN0P
#define PADA_GIN0P 184
#define GPIO_PAD_184 GPIO183
#ifndef PIN_18_IS_GPIO
#define PIN_18_IS_GPIO 0
#endif 
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO PIN_18_IS_GPIO
#endif 

#define PIN_19 PADA_GIN0M
#define PADA_GIN0M 187
#define GPIO_PAD_187 GPIO186
#ifndef PIN_19_IS_GPIO
#define PIN_19_IS_GPIO 0
#endif 
#ifndef PADA_GIN0M_IS_GPIO
#define PADA_GIN0M_IS_GPIO PIN_19_IS_GPIO
#endif 

#define PIN_20 PADA_RIN0P
#define PADA_RIN0P 178
#define GPIO_PAD_178 GPIO177
#ifndef PIN_20_IS_GPIO
#define PIN_20_IS_GPIO 0
#endif 
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO PIN_20_IS_GPIO
#endif 

#define PADA_RIN0M 9999
#ifndef PADA_RIN0M_IS_GPIO
#define PADA_RIN0M_IS_GPIO 0
#endif 

#define PIN_21 PADA_VSYNC0
#define PADA_VSYNC0 175
#define GPIO_PAD_175 GPIO174
#ifndef PIN_21_IS_GPIO
#define PIN_21_IS_GPIO 0
#endif 
#ifndef PADA_VSYNC0_IS_GPIO
#define PADA_VSYNC0_IS_GPIO PIN_21_IS_GPIO
#endif 

#define PIN_23 PADA_HSYNC1
#define PADA_HSYNC1 173
#define GPIO_PAD_173 GPIO172
#ifndef PIN_23_IS_GPIO
#define PIN_23_IS_GPIO 0
#endif 
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO PIN_23_IS_GPIO
#endif 

#define PIN_24 PADA_BIN1P
#define PADA_BIN1P 191
#define GPIO_PAD_191 GPIO190
#ifndef PIN_24_IS_GPIO
#define PIN_24_IS_GPIO 0
#endif 
#ifndef PADA_BIN1P_IS_GPIO
#define PADA_BIN1P_IS_GPIO PIN_24_IS_GPIO
#endif 

#define PADA_BIN1M 9999
#ifndef PADA_BIN1M_IS_GPIO
#define PADA_BIN1M_IS_GPIO 0
#endif 

#define PIN_25 PADA_GIN1P
#define PADA_GIN1P 185
#define GPIO_PAD_185 GPIO184
#ifndef PIN_25_IS_GPIO
#define PIN_25_IS_GPIO 0
#endif 
#ifndef PADA_GIN1P_IS_GPIO
#define PADA_GIN1P_IS_GPIO PIN_25_IS_GPIO
#endif 

#define PIN_26 PADA_GIN1M
#define PADA_GIN1M 188
#define GPIO_PAD_188 GPIO187
#ifndef PIN_26_IS_GPIO
#define PIN_26_IS_GPIO 0
#endif 
#ifndef PADA_GIN1M_IS_GPIO
#define PADA_GIN1M_IS_GPIO PIN_26_IS_GPIO
#endif 

#define PIN_27 PADA_RIN1P
#define PADA_RIN1P 179
#define GPIO_PAD_179 GPIO178
#ifndef PIN_27_IS_GPIO
#define PIN_27_IS_GPIO 0
#endif 
#ifndef PADA_RIN1P_IS_GPIO
#define PADA_RIN1P_IS_GPIO PIN_27_IS_GPIO
#endif 

#define PADA_RIN1M 9999
#ifndef PADA_RIN1M_IS_GPIO
#define PADA_RIN1M_IS_GPIO 0
#endif 

#define PIN_28 PADA_VSYNC1
#define PADA_VSYNC1 176
#define GPIO_PAD_176 GPIO175
#ifndef PIN_28_IS_GPIO
#define PIN_28_IS_GPIO 0
#endif 
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO PIN_28_IS_GPIO
#endif 

#define PIN_29 PADA_HSYNC2
#define PADA_HSYNC2 174
#define GPIO_PAD_174 GPIO173
#ifndef PIN_29_IS_GPIO
#define PIN_29_IS_GPIO 0
#endif 
#ifndef PADA_HSYNC2_IS_GPIO
#define PADA_HSYNC2_IS_GPIO PIN_29_IS_GPIO
#endif 

#define PIN_30 PADA_BIN2P
#define PADA_BIN2P 192
#define GPIO_PAD_192 GPIO191
#ifndef PIN_30_IS_GPIO
#define PIN_30_IS_GPIO 0
#endif 
#ifndef PADA_BIN2P_IS_GPIO
#define PADA_BIN2P_IS_GPIO PIN_30_IS_GPIO
#endif 

#define PADA_BIN2M 9999
#ifndef PADA_BIN2M_IS_GPIO
#define PADA_BIN2M_IS_GPIO 0
#endif 

#define PIN_31 PADA_GIN2P
#define PADA_GIN2P 186
#define GPIO_PAD_186 GPIO185
#ifndef PIN_31_IS_GPIO
#define PIN_31_IS_GPIO 0
#endif 
#ifndef PADA_GIN2P_IS_GPIO
#define PADA_GIN2P_IS_GPIO PIN_31_IS_GPIO
#endif 

#define PIN_32 PADA_GIN2M
#define PADA_GIN2M 189
#define GPIO_PAD_189 GPIO188
#ifndef PIN_32_IS_GPIO
#define PIN_32_IS_GPIO 0
#endif 
#ifndef PADA_GIN2M_IS_GPIO
#define PADA_GIN2M_IS_GPIO PIN_32_IS_GPIO
#endif 

#define PIN_33 PADA_RIN2P
#define PADA_RIN2P 180
#define GPIO_PAD_180 GPIO179
#ifndef PIN_33_IS_GPIO
#define PIN_33_IS_GPIO 0
#endif 
#ifndef PADA_RIN2P_IS_GPIO
#define PADA_RIN2P_IS_GPIO PIN_33_IS_GPIO
#endif 

#define PADA_RIN2M 9999
#ifndef PADA_RIN2M_IS_GPIO
#define PADA_RIN2M_IS_GPIO 0
#endif 

#define PIN_34 PADA_VSYNC2
#define PADA_VSYNC2 177
#define GPIO_PAD_177 GPIO176
#ifndef PIN_34_IS_GPIO
#define PIN_34_IS_GPIO 0
#endif 
#ifndef PADA_VSYNC2_IS_GPIO
#define PADA_VSYNC2_IS_GPIO PIN_34_IS_GPIO
#endif 

#define PIN_43 PAD_GPIO30
#define PAD_GPIO30 75
#define GPIO_PAD_75 GPIO74
#ifndef PIN_43_IS_GPIO
#define PIN_43_IS_GPIO 0
#endif 
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO PIN_43_IS_GPIO
#endif 

#define PIN_44 PAD_GPIO31
#define PAD_GPIO31 76
#define GPIO_PAD_76 GPIO75
#ifndef PIN_44_IS_GPIO
#define PIN_44_IS_GPIO 0
#endif 
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO PIN_44_IS_GPIO
#endif 

#define PIN_45 PAD_GPIO32
#define PAD_GPIO32 77
#define GPIO_PAD_77 GPIO76
#ifndef PIN_45_IS_GPIO
#define PIN_45_IS_GPIO 0
#endif 
#ifndef PAD_GPIO32_IS_GPIO
#define PAD_GPIO32_IS_GPIO PIN_45_IS_GPIO
#endif 

#define PIN_46 PAD_GPIO33
#define PAD_GPIO33 78
#define GPIO_PAD_78 GPIO77
#ifndef PIN_46_IS_GPIO
#define PIN_46_IS_GPIO 0
#endif 
#ifndef PAD_GPIO33_IS_GPIO
#define PAD_GPIO33_IS_GPIO PIN_46_IS_GPIO
#endif 

#define PIN_47 PAD_GPIO34
#define PAD_GPIO34 79
#define GPIO_PAD_79 GPIO78
#ifndef PIN_47_IS_GPIO
#define PIN_47_IS_GPIO 0
#endif 
#ifndef PAD_GPIO34_IS_GPIO
#define PAD_GPIO34_IS_GPIO PIN_47_IS_GPIO
#endif 

#define PIN_48 PAD_GPIO35
#define PAD_GPIO35 80
#define GPIO_PAD_80 GPIO79
#ifndef PIN_48_IS_GPIO
#define PIN_48_IS_GPIO 0
#endif 
#ifndef PAD_GPIO35_IS_GPIO
#define PAD_GPIO35_IS_GPIO PIN_48_IS_GPIO
#endif 

#define PAD_LINEIN_L1 9999
#ifndef PAD_LINEIN_L1_IS_GPIO
#define PAD_LINEIN_L1_IS_GPIO 0
#endif 

#define PAD_LINEIN_R1 9999
#ifndef PAD_LINEIN_R1_IS_GPIO
#define PAD_LINEIN_R1_IS_GPIO 0
#endif 

#define PIN_53 PAD_LINEIN_L2
#define PAD_LINEIN_L2 198
#define GPIO_PAD_198 GPIO197
#ifndef PIN_53_IS_GPIO
#define PIN_53_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L2_IS_GPIO
#define PAD_LINEIN_L2_IS_GPIO PIN_53_IS_GPIO
#endif 

#define PIN_54 PAD_LINEIN_R2
#define PAD_LINEIN_R2 199
#define GPIO_PAD_199 GPIO198
#ifndef PIN_54_IS_GPIO
#define PIN_54_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R2_IS_GPIO
#define PAD_LINEIN_R2_IS_GPIO PIN_54_IS_GPIO
#endif 

#define PIN_55 PAD_LINEIN_L3
#define PAD_LINEIN_L3 200
#define GPIO_PAD_200 GPIO199
#ifndef PIN_55_IS_GPIO
#define PIN_55_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L3_IS_GPIO
#define PAD_LINEIN_L3_IS_GPIO PIN_55_IS_GPIO
#endif 

#define PIN_56 PAD_LINEIN_R3
#define PAD_LINEIN_R3 201
#define GPIO_PAD_201 GPIO200
#ifndef PIN_56_IS_GPIO
#define PIN_56_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R3_IS_GPIO
#define PAD_LINEIN_R3_IS_GPIO PIN_56_IS_GPIO
#endif 

#define PIN_58 PAD_LINEIN_R4
#define PAD_LINEIN_R4 203
#define GPIO_PAD_203 GPIO202
#ifndef PIN_58_IS_GPIO
#define PIN_58_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_R4_IS_GPIO
#define PAD_LINEIN_R4_IS_GPIO PIN_58_IS_GPIO
#endif 

#define PIN_57 PAD_LINEIN_L4
#define PAD_LINEIN_L4 202
#define GPIO_PAD_202 GPIO201
#ifndef PIN_57_IS_GPIO
#define PIN_57_IS_GPIO 0
#endif 
#ifndef PAD_LINEIN_L4_IS_GPIO
#define PAD_LINEIN_L4_IS_GPIO PIN_57_IS_GPIO
#endif 

#define PAD_LINEIN_R5 9999
#ifndef PAD_LINEIN_R5_IS_GPIO
#define PAD_LINEIN_R5_IS_GPIO 0
#endif 

#define PAD_LINEIN_L5 9999
#ifndef PAD_LINEIN_L5_IS_GPIO
#define PAD_LINEIN_L5_IS_GPIO 0
#endif 

#define PAD_GPIO29 9999
#ifndef PAD_GPIO29_IS_GPIO
#define PAD_GPIO29_IS_GPIO 0
#endif 

#define PAD_GPIO28 9999
#ifndef PAD_GPIO28_IS_GPIO
#define PAD_GPIO28_IS_GPIO 0
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif 

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif 

#define PIN_78 PAD_GPIO24
#define PAD_GPIO24 69
#define GPIO_PAD_69 GPIO68
#ifndef PIN_78_IS_GPIO
#define PIN_78_IS_GPIO 0
#endif 
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO PIN_78_IS_GPIO
#endif 

#define PIN_80 PAD_GPIO0
#define PAD_GPIO0 45
#define GPIO_PAD_45 GPIO44
#ifndef PIN_80_IS_GPIO
#define PIN_80_IS_GPIO 0
#endif 
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO PIN_80_IS_GPIO
#endif 

#define PIN_81 PAD_GPIO1
#define PAD_GPIO1 46
#define GPIO_PAD_46 GPIO45
#ifndef PIN_81_IS_GPIO
#define PIN_81_IS_GPIO 0
#endif 
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO PIN_81_IS_GPIO
#endif 

#define PIN_82 PAD_GPIO2
#define PAD_GPIO2 47
#define GPIO_PAD_47 GPIO46
#ifndef PIN_82_IS_GPIO
#define PIN_82_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO PIN_82_IS_GPIO
#endif 

#define PIN_83 PAD_GPIO3
#define PAD_GPIO3 48
#define GPIO_PAD_48 GPIO47
#ifndef PIN_83_IS_GPIO
#define PIN_83_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO PIN_83_IS_GPIO
#endif 

#define PIN_84 PAD_GPIO4
#define PAD_GPIO4 49
#define GPIO_PAD_49 GPIO48
#ifndef PIN_84_IS_GPIO
#define PIN_84_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO PIN_84_IS_GPIO
#endif 

#define PIN_85 PAD_GPIO5
#define PAD_GPIO5 50
#define GPIO_PAD_50 GPIO49
#ifndef PIN_85_IS_GPIO
#define PIN_85_IS_GPIO 0
#endif 
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO PIN_85_IS_GPIO
#endif 

#define PIN_88 PAD_GPIO6
#define PAD_GPIO6 51
#define GPIO_PAD_51 GPIO50
#ifndef PIN_88_IS_GPIO
#define PIN_88_IS_GPIO 0
#endif 
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO PIN_88_IS_GPIO
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PIN_90 PAD_PCM_RESET
#define PAD_PCM_RESET 128
#define GPIO_PAD_128 GPIO127
#ifndef PIN_90_IS_GPIO
#define PIN_90_IS_GPIO 0
#endif 
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO PIN_90_IS_GPIO
#endif 

#define PIN_91 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 129
#define GPIO_PAD_129 GPIO128
#ifndef PIN_91_IS_GPIO
#define PIN_91_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO PIN_91_IS_GPIO
#endif 

#define PIN_92 PAD_PCM_CD_N
#define PAD_PCM_CD_N 130
#define GPIO_PAD_130 GPIO129
#ifndef PIN_92_IS_GPIO
#define PIN_92_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO PIN_92_IS_GPIO
#endif 

#define PIN_93 PAD_PCM_REG_N
#define PAD_PCM_REG_N 131
#define GPIO_PAD_131 GPIO130
#ifndef PIN_93_IS_GPIO
#define PIN_93_IS_GPIO 0
#endif 
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO PIN_93_IS_GPIO
#endif 

#define PIN_94 PAD_PCM_CE_N
#define PAD_PCM_CE_N 132
#define GPIO_PAD_132 GPIO131
#ifndef PIN_94_IS_GPIO
#define PIN_94_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO PIN_94_IS_GPIO
#endif 

#define PIN_95 PAD_PCM_OE_N
#define PAD_PCM_OE_N 133
#define GPIO_PAD_133 GPIO132
#ifndef PIN_95_IS_GPIO
#define PIN_95_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO PIN_95_IS_GPIO
#endif 

#define PIN_96 PAD_PCM_WE_N
#define PAD_PCM_WE_N 134
#define GPIO_PAD_134 GPIO133
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO PIN_96_IS_GPIO
#endif 

#define PIN_97 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 135
#define GPIO_PAD_135 GPIO134
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO PIN_97_IS_GPIO
#endif 

#define PIN_98 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 136
#define GPIO_PAD_136 GPIO135
#ifndef PIN_98_IS_GPIO
#define PIN_98_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO PIN_98_IS_GPIO
#endif 

#define PIN_100 PAD_PCM_D0
#define PAD_PCM_D0 137
#define GPIO_PAD_137 GPIO136
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO PIN_100_IS_GPIO
#endif 

#define PIN_101 PAD_PCM_D1
#define PAD_PCM_D1 138
#define GPIO_PAD_138 GPIO137
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO PIN_101_IS_GPIO
#endif 

#define PIN_102 PAD_PCM_D2
#define PAD_PCM_D2 139
#define GPIO_PAD_139 GPIO138
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO PIN_102_IS_GPIO
#endif 

#define PIN_103 PAD_PCM_D3
#define PAD_PCM_D3 140
#define GPIO_PAD_140 GPIO139
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO PIN_103_IS_GPIO
#endif 

#define PIN_104 PAD_PCM_D4
#define PAD_PCM_D4 141
#define GPIO_PAD_141 GPIO140
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO PIN_104_IS_GPIO
#endif 

#define PIN_105 PAD_PCM_D5
#define PAD_PCM_D5 142
#define GPIO_PAD_142 GPIO141
#ifndef PIN_105_IS_GPIO
#define PIN_105_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO PIN_105_IS_GPIO
#endif 

#define PIN_106 PAD_PCM_D6
#define PAD_PCM_D6 143
#define GPIO_PAD_143 GPIO142
#ifndef PIN_106_IS_GPIO
#define PIN_106_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO PIN_106_IS_GPIO
#endif 

#define PIN_107 PAD_PCM_D7
#define PAD_PCM_D7 144
#define GPIO_PAD_144 GPIO143
#ifndef PIN_107_IS_GPIO
#define PIN_107_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO PIN_107_IS_GPIO
#endif 

#define PIN_108 PAD_PCM_A14
#define PAD_PCM_A14 127
#define GPIO_PAD_127 GPIO126
#ifndef PIN_108_IS_GPIO
#define PIN_108_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO PIN_108_IS_GPIO
#endif 

#define PIN_109 PAD_PCM_A13
#define PAD_PCM_A13 126
#define GPIO_PAD_126 GPIO125
#ifndef PIN_109_IS_GPIO
#define PIN_109_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO PIN_109_IS_GPIO
#endif 

#define PIN_110 PAD_PCM_A12
#define PAD_PCM_A12 125
#define GPIO_PAD_125 GPIO124
#ifndef PIN_110_IS_GPIO
#define PIN_110_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO PIN_110_IS_GPIO
#endif 

#define PIN_111 PAD_PCM_A11
#define PAD_PCM_A11 124
#define GPIO_PAD_124 GPIO123
#ifndef PIN_111_IS_GPIO
#define PIN_111_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO PIN_111_IS_GPIO
#endif 

#define PIN_112 PAD_PCM_A10
#define PAD_PCM_A10 123
#define GPIO_PAD_123 GPIO122
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO PIN_112_IS_GPIO
#endif 

#define PIN_113 PAD_PCM_A9
#define PAD_PCM_A9 122
#define GPIO_PAD_122 GPIO121
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO PIN_113_IS_GPIO
#endif 

#define PIN_114 PAD_PCM_A8
#define PAD_PCM_A8 121
#define GPIO_PAD_121 GPIO120
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO PIN_114_IS_GPIO
#endif 

#define PIN_115 PAD_PCM_A7
#define PAD_PCM_A7 120
#define GPIO_PAD_120 GPIO119
#ifndef PIN_115_IS_GPIO
#define PIN_115_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO PIN_115_IS_GPIO
#endif 

#define PIN_116 PAD_PCM_A6
#define PAD_PCM_A6 119
#define GPIO_PAD_119 GPIO118
#ifndef PIN_116_IS_GPIO
#define PIN_116_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO PIN_116_IS_GPIO
#endif 

#define PIN_117 PAD_PCM_A5
#define PAD_PCM_A5 118
#define GPIO_PAD_118 GPIO117
#ifndef PIN_117_IS_GPIO
#define PIN_117_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO PIN_117_IS_GPIO
#endif 

#define PIN_118 PAD_PCM_A4
#define PAD_PCM_A4 117
#define GPIO_PAD_117 GPIO116
#ifndef PIN_118_IS_GPIO
#define PIN_118_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO PIN_118_IS_GPIO
#endif 

#define PIN_119 PAD_PCM_A3
#define PAD_PCM_A3 116
#define GPIO_PAD_116 GPIO115
#ifndef PIN_119_IS_GPIO
#define PIN_119_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO PIN_119_IS_GPIO
#endif 

#define PIN_120 PAD_PCM_A2
#define PAD_PCM_A2 115
#define GPIO_PAD_115 GPIO114
#ifndef PIN_120_IS_GPIO
#define PIN_120_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO PIN_120_IS_GPIO
#endif 

#define PIN_121 PAD_PCM_A1
#define PAD_PCM_A1 114
#define GPIO_PAD_114 GPIO113
#ifndef PIN_121_IS_GPIO
#define PIN_121_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO PIN_121_IS_GPIO
#endif 

#define PIN_122 PAD_PCM_A0
#define PAD_PCM_A0 113
#define GPIO_PAD_113 GPIO112
#ifndef PIN_122_IS_GPIO
#define PIN_122_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO PIN_122_IS_GPIO
#endif 

#define PIN_123 PAD_NAND_AD7
#define PAD_NAND_AD7 112
#define GPIO_PAD_112 GPIO111
#ifndef PIN_123_IS_GPIO
#define PIN_123_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD7_IS_GPIO
#define PAD_NAND_AD7_IS_GPIO PIN_123_IS_GPIO
#endif 

#define PIN_124 PAD_NAND_AD6
#define PAD_NAND_AD6 111
#define GPIO_PAD_111 GPIO110
#ifndef PIN_124_IS_GPIO
#define PIN_124_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD6_IS_GPIO
#define PAD_NAND_AD6_IS_GPIO PIN_124_IS_GPIO
#endif 

#define PIN_125 PAD_NAND_AD5
#define PAD_NAND_AD5 110
#define GPIO_PAD_110 GPIO109
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD5_IS_GPIO
#define PAD_NAND_AD5_IS_GPIO PIN_125_IS_GPIO
#endif 

#define PIN_126 PAD_NAND_AD4
#define PAD_NAND_AD4 109
#define GPIO_PAD_109 GPIO108
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD4_IS_GPIO
#define PAD_NAND_AD4_IS_GPIO PIN_126_IS_GPIO
#endif 

#define PIN_127 PAD_NAND_AD3
#define PAD_NAND_AD3 108
#define GPIO_PAD_108 GPIO107
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD3_IS_GPIO
#define PAD_NAND_AD3_IS_GPIO PIN_127_IS_GPIO
#endif 

#define PIN_128 PAD_NAND_AD2
#define PAD_NAND_AD2 107
#define GPIO_PAD_107 GPIO106
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD2_IS_GPIO
#define PAD_NAND_AD2_IS_GPIO PIN_128_IS_GPIO
#endif 

#define PIN_129 PAD_NAND_AD1
#define PAD_NAND_AD1 106
#define GPIO_PAD_106 GPIO105
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD1_IS_GPIO
#define PAD_NAND_AD1_IS_GPIO PIN_129_IS_GPIO
#endif 

#define PIN_130 PAD_NAND_AD0
#define PAD_NAND_AD0 105
#define GPIO_PAD_105 GPIO104
#ifndef PIN_130_IS_GPIO
#define PIN_130_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD0_IS_GPIO
#define PAD_NAND_AD0_IS_GPIO PIN_130_IS_GPIO
#endif 

#define PIN_131 PAD_TS0_CLK
#define PAD_TS0_CLK 155
#define GPIO_PAD_155 GPIO154
#ifndef PIN_131_IS_GPIO
#define PIN_131_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO PIN_131_IS_GPIO
#endif 

#define PIN_132 PAD_TS0_SYNC
#define PAD_TS0_SYNC 154
#define GPIO_PAD_154 GPIO153
#ifndef PIN_132_IS_GPIO
#define PIN_132_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO PIN_132_IS_GPIO
#endif 

#define PIN_133 PAD_TS0_VLD
#define PAD_TS0_VLD 153
#define GPIO_PAD_153 GPIO152
#ifndef PIN_133_IS_GPIO
#define PIN_133_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO PIN_133_IS_GPIO
#endif 

#define PIN_134 PAD_TS0_D7
#define PAD_TS0_D7 152
#define GPIO_PAD_152 GPIO151
#ifndef PIN_134_IS_GPIO
#define PIN_134_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO PIN_134_IS_GPIO
#endif 

#define PIN_135 PAD_TS0_D6
#define PAD_TS0_D6 151
#define GPIO_PAD_151 GPIO150
#ifndef PIN_135_IS_GPIO
#define PIN_135_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO PIN_135_IS_GPIO
#endif 

#define PIN_136 PAD_TS0_D5
#define PAD_TS0_D5 150
#define GPIO_PAD_150 GPIO149
#ifndef PIN_136_IS_GPIO
#define PIN_136_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO PIN_136_IS_GPIO
#endif 

#define PIN_137 PAD_TS0_D4
#define PAD_TS0_D4 149
#define GPIO_PAD_149 GPIO148
#ifndef PIN_137_IS_GPIO
#define PIN_137_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO PIN_137_IS_GPIO
#endif 

#define PIN_138 PAD_TS0_D3
#define PAD_TS0_D3 148
#define GPIO_PAD_148 GPIO147
#ifndef PIN_138_IS_GPIO
#define PIN_138_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO PIN_138_IS_GPIO
#endif 

#define PIN_139 PAD_TS0_D2
#define PAD_TS0_D2 147
#define GPIO_PAD_147 GPIO146
#ifndef PIN_139_IS_GPIO
#define PIN_139_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO PIN_139_IS_GPIO
#endif 

#define PIN_140 PAD_TS0_D1
#define PAD_TS0_D1 146
#define GPIO_PAD_146 GPIO145
#ifndef PIN_140_IS_GPIO
#define PIN_140_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO PIN_140_IS_GPIO
#endif 

#define PIN_141 PAD_TS0_D0
#define PAD_TS0_D0 145
#define GPIO_PAD_145 GPIO144
#ifndef PIN_141_IS_GPIO
#define PIN_141_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO PIN_141_IS_GPIO
#endif 

#define PIN_142 PAD_TS1_CLK
#define PAD_TS1_CLK 166
#define GPIO_PAD_166 GPIO165
#ifndef PIN_142_IS_GPIO
#define PIN_142_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO PIN_142_IS_GPIO
#endif 

#define PIN_143 PAD_TS1_SYNC
#define PAD_TS1_SYNC 165
#define GPIO_PAD_165 GPIO164
#ifndef PIN_143_IS_GPIO
#define PIN_143_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO PIN_143_IS_GPIO
#endif 

#define PIN_144 PAD_TS1_VLD
#define PAD_TS1_VLD 164
#define GPIO_PAD_164 GPIO163
#ifndef PIN_144_IS_GPIO
#define PIN_144_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO PIN_144_IS_GPIO
#endif 

#define PIN_145 PAD_TS1_D7
#define PAD_TS1_D7 163
#define GPIO_PAD_163 GPIO162
#ifndef PIN_145_IS_GPIO
#define PIN_145_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO PIN_145_IS_GPIO
#endif 

#define PIN_146 PAD_TS1_D6
#define PAD_TS1_D6 162
#define GPIO_PAD_162 GPIO161
#ifndef PIN_146_IS_GPIO
#define PIN_146_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO PIN_146_IS_GPIO
#endif 

#define PIN_147 PAD_TS1_D5
#define PAD_TS1_D5 161
#define GPIO_PAD_161 GPIO160
#ifndef PIN_147_IS_GPIO
#define PIN_147_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO PIN_147_IS_GPIO
#endif 

#define PIN_148 PAD_TS1_D4
#define PAD_TS1_D4 160
#define GPIO_PAD_160 GPIO159
#ifndef PIN_148_IS_GPIO
#define PIN_148_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO PIN_148_IS_GPIO
#endif 

#define PIN_149 PAD_TS1_D3
#define PAD_TS1_D3 159
#define GPIO_PAD_159 GPIO158
#ifndef PIN_149_IS_GPIO
#define PIN_149_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO PIN_149_IS_GPIO
#endif 

#define PIN_150 PAD_TS1_D2
#define PAD_TS1_D2 158
#define GPIO_PAD_158 GPIO157
#ifndef PIN_150_IS_GPIO
#define PIN_150_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO PIN_150_IS_GPIO
#endif 

#define PIN_151 PAD_TS1_D1
#define PAD_TS1_D1 157
#define GPIO_PAD_157 GPIO156
#ifndef PIN_151_IS_GPIO
#define PIN_151_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO PIN_151_IS_GPIO
#endif 

#define PIN_152 PAD_TS1_D0
#define PAD_TS1_D0 156
#define GPIO_PAD_156 GPIO155
#ifndef PIN_152_IS_GPIO
#define PIN_152_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO PIN_152_IS_GPIO
#endif 

#define PIN_153 PAD_TS2_CLK
#define PAD_TS2_CLK 170
#define GPIO_PAD_170 GPIO169
#ifndef PIN_153_IS_GPIO
#define PIN_153_IS_GPIO 0
#endif 
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO PIN_153_IS_GPIO
#endif 

#define PIN_154 PAD_TS2_SYNC
#define PAD_TS2_SYNC 169
#define GPIO_PAD_169 GPIO168
#ifndef PIN_154_IS_GPIO
#define PIN_154_IS_GPIO 0
#endif 
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO PIN_154_IS_GPIO
#endif 

#define PIN_155 PAD_TS2_VLD
#define PAD_TS2_VLD 168
#define GPIO_PAD_168 GPIO167
#ifndef PIN_155_IS_GPIO
#define PIN_155_IS_GPIO 0
#endif 
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO PIN_155_IS_GPIO
#endif 

#define PIN_156 PAD_TS2_D
#define PAD_TS2_D 167
#define GPIO_PAD_167 GPIO166
#ifndef PIN_156_IS_GPIO
#define PIN_156_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D_IS_GPIO
#define PAD_TS2_D_IS_GPIO PIN_156_IS_GPIO
#endif 

#define PIN_161 PAD_B_ODD0
#define PAD_B_ODD0 44
#define GPIO_PAD_44 GPIO43
#ifndef PIN_161_IS_GPIO
#define PIN_161_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO PIN_161_IS_GPIO
#endif 

#define PIN_162 PAD_B_ODD1
#define PAD_B_ODD1 43
#define GPIO_PAD_43 GPIO42
#ifndef PIN_162_IS_GPIO
#define PIN_162_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO PIN_162_IS_GPIO
#endif 

#define PIN_163 PAD_B_ODD2
#define PAD_B_ODD2 42
#define GPIO_PAD_42 GPIO41
#ifndef PIN_163_IS_GPIO
#define PIN_163_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO PIN_163_IS_GPIO
#endif 

#define PIN_164 PAD_B_ODD3
#define PAD_B_ODD3 41
#define GPIO_PAD_41 GPIO40
#ifndef PIN_164_IS_GPIO
#define PIN_164_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO PIN_164_IS_GPIO
#endif 

#define PIN_165 PAD_B_ODD4
#define PAD_B_ODD4 40
#define GPIO_PAD_40 GPIO39
#ifndef PIN_165_IS_GPIO
#define PIN_165_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO PIN_165_IS_GPIO
#endif 

#define PIN_166 PAD_B_ODD5
#define PAD_B_ODD5 39
#define GPIO_PAD_39 GPIO38
#ifndef PIN_166_IS_GPIO
#define PIN_166_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO PIN_166_IS_GPIO
#endif 

#define PIN_167 PAD_B_ODD6
#define PAD_B_ODD6 38
#define GPIO_PAD_38 GPIO37
#ifndef PIN_167_IS_GPIO
#define PIN_167_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO PIN_167_IS_GPIO
#endif 

#define PIN_168 PAD_B_ODD7
#define PAD_B_ODD7 37
#define GPIO_PAD_37 GPIO36
#ifndef PIN_168_IS_GPIO
#define PIN_168_IS_GPIO 0
#endif 
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO PIN_168_IS_GPIO
#endif 

#define PIN_169 PAD_G_ODD0
#define PAD_G_ODD0 36
#define GPIO_PAD_36 GPIO35
#ifndef PIN_169_IS_GPIO
#define PIN_169_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO PIN_169_IS_GPIO
#endif 

#define PIN_170 PAD_G_ODD1
#define PAD_G_ODD1 35
#define GPIO_PAD_35 GPIO34
#ifndef PIN_170_IS_GPIO
#define PIN_170_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO PIN_170_IS_GPIO
#endif 

#define PIN_171 PAD_G_ODD2
#define PAD_G_ODD2 34
#define GPIO_PAD_34 GPIO33
#ifndef PIN_171_IS_GPIO
#define PIN_171_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO PIN_171_IS_GPIO
#endif 

#define PIN_172 PAD_G_ODD3
#define PAD_G_ODD3 33
#define GPIO_PAD_33 GPIO32
#ifndef PIN_172_IS_GPIO
#define PIN_172_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO PIN_172_IS_GPIO
#endif 

#define PIN_173 PAD_G_ODD4
#define PAD_G_ODD4 32
#define GPIO_PAD_32 GPIO31
#ifndef PIN_173_IS_GPIO
#define PIN_173_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO PIN_173_IS_GPIO
#endif 

#define PIN_174 PAD_G_ODD5
#define PAD_G_ODD5 31
#define GPIO_PAD_31 GPIO30
#ifndef PIN_174_IS_GPIO
#define PIN_174_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO PIN_174_IS_GPIO
#endif 

#define PIN_175 PAD_G_ODD6
#define PAD_G_ODD6 30
#define GPIO_PAD_30 GPIO29
#ifndef PIN_175_IS_GPIO
#define PIN_175_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO PIN_175_IS_GPIO
#endif 

#define PIN_176 PAD_G_ODD7
#define PAD_G_ODD7 29
#define GPIO_PAD_29 GPIO28
#ifndef PIN_176_IS_GPIO
#define PIN_176_IS_GPIO 0
#endif 
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO PIN_176_IS_GPIO
#endif 

#define PIN_177 PAD_R_ODD0
#define PAD_R_ODD0 28
#define GPIO_PAD_28 GPIO27
#ifndef PIN_177_IS_GPIO
#define PIN_177_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO PIN_177_IS_GPIO
#endif 

#define PIN_178 PAD_R_ODD1
#define PAD_R_ODD1 27
#define GPIO_PAD_27 GPIO26
#ifndef PIN_178_IS_GPIO
#define PIN_178_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO PIN_178_IS_GPIO
#endif 

#define PIN_179 PAD_R_ODD2
#define PAD_R_ODD2 26
#define GPIO_PAD_26 GPIO25
#ifndef PIN_179_IS_GPIO
#define PIN_179_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO PIN_179_IS_GPIO
#endif 

#define PIN_180 PAD_R_ODD3
#define PAD_R_ODD3 25
#define GPIO_PAD_25 GPIO24
#ifndef PIN_180_IS_GPIO
#define PIN_180_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO PIN_180_IS_GPIO
#endif 

#define PIN_182 PAD_R_ODD4
#define PAD_R_ODD4 24
#define GPIO_PAD_24 GPIO23
#ifndef PIN_182_IS_GPIO
#define PIN_182_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO PIN_182_IS_GPIO
#endif 

#define PIN_183 PAD_R_ODD5
#define PAD_R_ODD5 23
#define GPIO_PAD_23 GPIO22
#ifndef PIN_183_IS_GPIO
#define PIN_183_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO PIN_183_IS_GPIO
#endif 

#define PIN_184 PAD_R_ODD6
#define PAD_R_ODD6 22
#define GPIO_PAD_22 GPIO21
#ifndef PIN_184_IS_GPIO
#define PIN_184_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO PIN_184_IS_GPIO
#endif 

#define PIN_185 PAD_R_ODD7
#define PAD_R_ODD7 21
#define GPIO_PAD_21 GPIO20
#ifndef PIN_185_IS_GPIO
#define PIN_185_IS_GPIO 0
#endif 
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO PIN_185_IS_GPIO
#endif 

#define PIN_186 PAD_LCK
#define PAD_LCK 20
#define GPIO_PAD_20 GPIO19
#ifndef PIN_186_IS_GPIO
#define PIN_186_IS_GPIO 0
#endif 
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO PIN_186_IS_GPIO
#endif 

#define PIN_187 PAD_LDE
#define PAD_LDE 19
#define GPIO_PAD_19 GPIO18
#ifndef PIN_187_IS_GPIO
#define PIN_187_IS_GPIO 0
#endif 
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO PIN_187_IS_GPIO
#endif 

#define PIN_188 PAD_LHSYNC
#define PAD_LHSYNC 18
#define GPIO_PAD_18 GPIO17
#ifndef PIN_188_IS_GPIO
#define PIN_188_IS_GPIO 0
#endif 
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO PIN_188_IS_GPIO
#endif 

#define PIN_189 PAD_LVSYNC
#define PAD_LVSYNC 17
#define GPIO_PAD_17 GPIO16
#ifndef PIN_189_IS_GPIO
#define PIN_189_IS_GPIO 0
#endif 
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO PIN_189_IS_GPIO
#endif 

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif 

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif 

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif 

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif 

#define PIN_191 PAD_TCON7
#define PAD_TCON7 8
#define GPIO_PAD_8 GPIO7
#ifndef PIN_191_IS_GPIO
#define PIN_191_IS_GPIO 0
#endif 
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO PIN_191_IS_GPIO
#endif 

#define PIN_192 PAD_TCON6
#define PAD_TCON6 7
#define GPIO_PAD_7 GPIO6
#ifndef PIN_192_IS_GPIO
#define PIN_192_IS_GPIO 0
#endif 
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO PIN_192_IS_GPIO
#endif 

#define PIN_193 PAD_TCON5
#define PAD_TCON5 6
#define GPIO_PAD_6 GPIO5
#ifndef PIN_193_IS_GPIO
#define PIN_193_IS_GPIO 0
#endif 
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO PIN_193_IS_GPIO
#endif 

#define PIN_194 PAD_TCON4
#define PAD_TCON4 5
#define GPIO_PAD_5 GPIO4
#ifndef PIN_194_IS_GPIO
#define PIN_194_IS_GPIO 0
#endif 
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO PIN_194_IS_GPIO
#endif 

#define PIN_195 PAD_TCON3
#define PAD_TCON3 4
#define GPIO_PAD_4 GPIO3
#ifndef PIN_195_IS_GPIO
#define PIN_195_IS_GPIO 0
#endif 
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO PIN_195_IS_GPIO
#endif 

#define PIN_196 PAD_TCON2
#define PAD_TCON2 3
#define GPIO_PAD_3 GPIO2
#ifndef PIN_196_IS_GPIO
#define PIN_196_IS_GPIO 0
#endif 
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO PIN_196_IS_GPIO
#endif 

#define PIN_197 PAD_TCON1
#define PAD_TCON1 2
#define GPIO_PAD_2 GPIO1
#ifndef PIN_197_IS_GPIO
#define PIN_197_IS_GPIO 0
#endif 
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO PIN_197_IS_GPIO
#endif 

#define PIN_198 PAD_TCON0
#define PAD_TCON0 1
#define GPIO_PAD_1 GPIO0
#ifndef PIN_198_IS_GPIO
#define PIN_198_IS_GPIO 0
#endif 
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO PIN_198_IS_GPIO
#endif 

#define PAD_INT 9999
#ifndef PAD_INT_IS_GPIO
#define PAD_INT_IS_GPIO 0
#endif 

#define PIN_201 PAD_PWM0
#define PAD_PWM0 16
#define GPIO_PAD_16 GPIO15
#ifndef PIN_201_IS_GPIO
#define PIN_201_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_201_IS_GPIO
#endif 

#define PIN_202 PAD_PWM1
#define PAD_PWM1 15
#define GPIO_PAD_15 GPIO14
#ifndef PIN_202_IS_GPIO
#define PIN_202_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_202_IS_GPIO
#endif 

#define PIN_204 PAD_NAND_CEZ
#define PAD_NAND_CEZ 101
#define GPIO_PAD_101 GPIO100
#ifndef PIN_204_IS_GPIO
#define PIN_204_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO PIN_204_IS_GPIO
#endif 

#define PIN_205 PAD_NAND_CLE
#define PAD_NAND_CLE 100
#define GPIO_PAD_100 GPIO99
#ifndef PIN_205_IS_GPIO
#define PIN_205_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CLE_IS_GPIO
#define PAD_NAND_CLE_IS_GPIO PIN_205_IS_GPIO
#endif 

#define PIN_206 PAD_NAND_REZ
#define PAD_NAND_REZ 98
#define GPIO_PAD_98 GPIO97
#ifndef PIN_206_IS_GPIO
#define PIN_206_IS_GPIO 0
#endif 
#ifndef PAD_NAND_REZ_IS_GPIO
#define PAD_NAND_REZ_IS_GPIO PIN_206_IS_GPIO
#endif 

#define PIN_207 PAD_NAND_WEZ
#define PAD_NAND_WEZ 103
#define GPIO_PAD_103 GPIO102
#ifndef PIN_207_IS_GPIO
#define PIN_207_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WEZ_IS_GPIO
#define PAD_NAND_WEZ_IS_GPIO PIN_207_IS_GPIO
#endif 

#define PIN_208 PAD_NAND_WPZ
#define PAD_NAND_WPZ 102
#define GPIO_PAD_102 GPIO101
#ifndef PIN_208_IS_GPIO
#define PIN_208_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WPZ_IS_GPIO
#define PAD_NAND_WPZ_IS_GPIO PIN_208_IS_GPIO
#endif 

#define PIN_209 PAD_NAND_ALE
#define PAD_NAND_ALE 99
#define GPIO_PAD_99 GPIO98
#ifndef PIN_209_IS_GPIO
#define PIN_209_IS_GPIO 0
#endif 
#ifndef PAD_NAND_ALE_IS_GPIO
#define PAD_NAND_ALE_IS_GPIO PIN_209_IS_GPIO
#endif 

#define PIN_210 PAD_NAND_RBZ
#define PAD_NAND_RBZ 104
#define GPIO_PAD_104 GPIO103
#ifndef PIN_210_IS_GPIO
#define PIN_210_IS_GPIO 0
#endif 
#ifndef PAD_NAND_RBZ_IS_GPIO
#define PAD_NAND_RBZ_IS_GPIO PIN_210_IS_GPIO
#endif 

#define PIN_211 PAD_PM_SPI_CZ2
#define PAD_PM_SPI_CZ2 97
#define GPIO_PAD_97 GPIO96
#ifndef PIN_211_IS_GPIO
#define PIN_211_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ2_IS_GPIO
#define PAD_PM_SPI_CZ2_IS_GPIO PIN_211_IS_GPIO
#endif 

#define PIN_212 PAD_PM_SPI_CZ1
#define PAD_PM_SPI_CZ1 96
#define GPIO_PAD_96 GPIO95
#ifndef PIN_212_IS_GPIO
#define PIN_212_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ1_IS_GPIO
#define PAD_PM_SPI_CZ1_IS_GPIO PIN_212_IS_GPIO
#endif 

#define PIN_215 PAD_MHL_DET
#define PAD_MHL_DET 95
#define GPIO_PAD_95 GPIO94
#ifndef PIN_215_IS_GPIO
#define PIN_215_IS_GPIO 0
#endif 
#ifndef PAD_MHL_DET_IS_GPIO
#define PAD_MHL_DET_IS_GPIO PIN_215_IS_GPIO
#endif 

#define PIN_216 PAD_DDCDC_CLK
#define PAD_DDCDC_CLK 92
#define GPIO_PAD_92 GPIO91
#ifndef PIN_216_IS_GPIO
#define PIN_216_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CLK_IS_GPIO
#define PAD_DDCDC_CLK_IS_GPIO PIN_216_IS_GPIO
#endif 

#define PIN_217 PAD_DDCDC_DAT
#define PAD_DDCDC_DAT 93
#define GPIO_PAD_93 GPIO92
#ifndef PIN_217_IS_GPIO
#define PIN_217_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DAT_IS_GPIO
#define PAD_DDCDC_DAT_IS_GPIO PIN_217_IS_GPIO
#endif 

#define PIN_218 PAD_SAR0
#define PAD_SAR0 85
#define GPIO_PAD_85 GPIO84
#ifndef PIN_218_IS_GPIO
#define PIN_218_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_218_IS_GPIO
#endif 

#define PIN_219 PAD_SAR1
#define PAD_SAR1 84
#define GPIO_PAD_84 GPIO83
#ifndef PIN_219_IS_GPIO
#define PIN_219_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_219_IS_GPIO
#endif 

#define PIN_220 PAD_SAR2
#define PAD_SAR2 83
#define GPIO_PAD_83 GPIO82
#ifndef PIN_220_IS_GPIO
#define PIN_220_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO PIN_220_IS_GPIO
#endif 

#define PIN_229 PAD_RN
#define PAD_RN 233
#define GPIO_PAD_233 GPIO232
#ifndef PIN_229_IS_GPIO
#define PIN_229_IS_GPIO 0
#endif 
#ifndef PAD_RN_IS_GPIO
#define PAD_RN_IS_GPIO PIN_229_IS_GPIO
#endif 

#define PIN_230 PAD_RP
#define PAD_RP 232
#define GPIO_PAD_232 GPIO231
#ifndef PIN_230_IS_GPIO
#define PIN_230_IS_GPIO 0
#endif 
#ifndef PAD_RP_IS_GPIO
#define PAD_RP_IS_GPIO PIN_230_IS_GPIO
#endif 

#define PIN_231 PAD_TN
#define PAD_TN 231
#define GPIO_PAD_231 GPIO230
#ifndef PIN_231_IS_GPIO
#define PIN_231_IS_GPIO 0
#endif 
#ifndef PAD_TN_IS_GPIO
#define PAD_TN_IS_GPIO PIN_231_IS_GPIO
#endif 

#define PIN_232 PAD_TP
#define PAD_TP 230
#define GPIO_PAD_230 GPIO229
#ifndef PIN_232_IS_GPIO
#define PIN_232_IS_GPIO 0
#endif 
#ifndef PAD_TP_IS_GPIO
#define PAD_TP_IS_GPIO PIN_232_IS_GPIO
#endif 

#define PIN_234 PAD_GPIO11
#define PAD_GPIO11 56
#define GPIO_PAD_56 GPIO55
#ifndef PIN_234_IS_GPIO
#define PIN_234_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO PIN_234_IS_GPIO
#endif 

#define PIN_235 PAD_GPIO10
#define PAD_GPIO10 55
#define GPIO_PAD_55 GPIO54
#ifndef PIN_235_IS_GPIO
#define PIN_235_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO PIN_235_IS_GPIO
#endif 

#define PIN_236 PAD_DDCDB_DAT
#define PAD_DDCDB_DAT 90
#define GPIO_PAD_90 GPIO89
#ifndef PIN_236_IS_GPIO
#define PIN_236_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DAT_IS_GPIO
#define PAD_DDCDB_DAT_IS_GPIO PIN_236_IS_GPIO
#endif 

#define PIN_237 PAD_DDCDB_CLK
#define PAD_DDCDB_CLK 89
#define GPIO_PAD_89 GPIO88
#ifndef PIN_237_IS_GPIO
#define PIN_237_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CLK_IS_GPIO
#define PAD_DDCDB_CLK_IS_GPIO PIN_237_IS_GPIO
#endif 

#define PIN_238 PAD_DDCDA_DAT
#define PAD_DDCDA_DAT 87
#define GPIO_PAD_87 GPIO86
#ifndef PIN_238_IS_GPIO
#define PIN_238_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DAT_IS_GPIO
#define PAD_DDCDA_DAT_IS_GPIO PIN_238_IS_GPIO
#endif 

#define PIN_239 PAD_DDCDA_CLK
#define PAD_DDCDA_CLK 86
#define GPIO_PAD_86 GPIO85
#ifndef PIN_239_IS_GPIO
#define PIN_239_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CLK_IS_GPIO
#define PAD_DDCDA_CLK_IS_GPIO PIN_239_IS_GPIO
#endif 

#define PIN_240 PAD_CEC
#define PAD_CEC 82
#define GPIO_PAD_82 GPIO81
#ifndef PIN_240_IS_GPIO
#define PIN_240_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO PIN_240_IS_GPIO
#endif 

#define PIN_241 PAD_HOTPLUG_C
#define PAD_HOTPLUG_C 94
#define GPIO_PAD_94 GPIO93
#ifndef PIN_241_IS_GPIO
#define PIN_241_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUG_C_IS_GPIO
#define PAD_HOTPLUG_C_IS_GPIO PIN_241_IS_GPIO
#endif 

#define PIN_242 PAD_HOTPLUG_B
#define PAD_HOTPLUG_B 91
#define GPIO_PAD_91 GPIO90
#ifndef PIN_242_IS_GPIO
#define PIN_242_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUG_B_IS_GPIO
#define PAD_HOTPLUG_B_IS_GPIO PIN_242_IS_GPIO
#endif 

#define PIN_243 PAD_HOTPLUG_A
#define PAD_HOTPLUG_A 88
#define GPIO_PAD_88 GPIO87
#ifndef PIN_243_IS_GPIO
#define PIN_243_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUG_A_IS_GPIO
#define PAD_HOTPLUG_A_IS_GPIO PIN_243_IS_GPIO
#endif 

#define PIN_245 PAD_ARC
#define PAD_ARC 171
#define GPIO_PAD_171 GPIO170
#ifndef PIN_245_IS_GPIO
#define PIN_245_IS_GPIO 0
#endif 
#ifndef PAD_ARC_IS_GPIO
#define PAD_ARC_IS_GPIO PIN_245_IS_GPIO
#endif 

#define PIN_247 PAD_RXCN_D
#define PAD_RXCN_D 222
#define GPIO_PAD_222 GPIO221
#ifndef PIN_247_IS_GPIO
#define PIN_247_IS_GPIO 0
#endif 
#ifndef PAD_RXCN_D_IS_GPIO
#define PAD_RXCN_D_IS_GPIO PIN_247_IS_GPIO
#endif 

#define PIN_249 PAD_RX0N_D
#define PAD_RX0N_D 223
#define GPIO_PAD_223 GPIO222
#ifndef PIN_249_IS_GPIO
#define PIN_249_IS_GPIO 0
#endif 
#ifndef PAD_RX0N_D_IS_GPIO
#define PAD_RX0N_D_IS_GPIO PIN_249_IS_GPIO
#endif 

#define PIN_248 PAD_RXCP_D
#define PAD_RXCP_D 226
#define GPIO_PAD_226 GPIO225
#ifndef PIN_248_IS_GPIO
#define PIN_248_IS_GPIO 0
#endif 
#ifndef PAD_RXCP_D_IS_GPIO
#define PAD_RXCP_D_IS_GPIO PIN_248_IS_GPIO
#endif 

#define PIN_250 PAD_RX0P_D
#define PAD_RX0P_D 227
#define GPIO_PAD_227 GPIO226
#ifndef PIN_250_IS_GPIO
#define PIN_250_IS_GPIO 0
#endif 
#ifndef PAD_RX0P_D_IS_GPIO
#define PAD_RX0P_D_IS_GPIO PIN_250_IS_GPIO
#endif 

#define PIN_251 PAD_RX1N_D
#define PAD_RX1N_D 224
#define GPIO_PAD_224 GPIO223
#ifndef PIN_251_IS_GPIO
#define PIN_251_IS_GPIO 0
#endif 
#ifndef PAD_RX1N_D_IS_GPIO
#define PAD_RX1N_D_IS_GPIO PIN_251_IS_GPIO
#endif 

#define PIN_253 PAD_RX2N_D
#define PAD_RX2N_D 225
#define GPIO_PAD_225 GPIO224
#ifndef PIN_253_IS_GPIO
#define PIN_253_IS_GPIO 0
#endif 
#ifndef PAD_RX2N_D_IS_GPIO
#define PAD_RX2N_D_IS_GPIO PIN_253_IS_GPIO
#endif 

#define PIN_252 PAD_RX1P_D
#define PAD_RX1P_D 228
#define GPIO_PAD_228 GPIO227
#ifndef PIN_252_IS_GPIO
#define PIN_252_IS_GPIO 0
#endif 
#ifndef PAD_RX1P_D_IS_GPIO
#define PAD_RX1P_D_IS_GPIO PIN_252_IS_GPIO
#endif 

#define PIN_254 PAD_RX2P_D
#define PAD_RX2P_D 229
#define GPIO_PAD_229 GPIO228
#ifndef PIN_254_IS_GPIO
#define PIN_254_IS_GPIO 0
#endif 
#ifndef PAD_RX2P_D_IS_GPIO
#define PAD_RX2P_D_IS_GPIO PIN_254_IS_GPIO
#endif 

#define PIN_1 PAD_RX0N_B
#define PAD_RX0N_B 215
#define GPIO_PAD_215 GPIO214
#ifndef PIN_1_IS_GPIO
#define PIN_1_IS_GPIO 0
#endif 
#ifndef PAD_RX0N_B_IS_GPIO
#define PAD_RX0N_B_IS_GPIO PIN_1_IS_GPIO
#endif 

#define PIN_255 PAD_RXCN_B
#define PAD_RXCN_B 214
#define GPIO_PAD_214 GPIO213
#ifndef PIN_255_IS_GPIO
#define PIN_255_IS_GPIO 0
#endif 
#ifndef PAD_RXCN_B_IS_GPIO
#define PAD_RXCN_B_IS_GPIO PIN_255_IS_GPIO
#endif 

#define PIN_2 PAD_RX0P_B
#define PAD_RX0P_B 219
#define GPIO_PAD_219 GPIO218
#ifndef PIN_2_IS_GPIO
#define PIN_2_IS_GPIO 0
#endif 
#ifndef PAD_RX0P_B_IS_GPIO
#define PAD_RX0P_B_IS_GPIO PIN_2_IS_GPIO
#endif 

#define PIN_256 PAD_RXCP_B
#define PAD_RXCP_B 218
#define GPIO_PAD_218 GPIO217
#ifndef PIN_256_IS_GPIO
#define PIN_256_IS_GPIO 0
#endif 
#ifndef PAD_RXCP_B_IS_GPIO
#define PAD_RXCP_B_IS_GPIO PIN_256_IS_GPIO
#endif 

#define PIN_5 PAD_RX2N_B
#define PAD_RX2N_B 217
#define GPIO_PAD_217 GPIO216
#ifndef PIN_5_IS_GPIO
#define PIN_5_IS_GPIO 0
#endif 
#ifndef PAD_RX2N_B_IS_GPIO
#define PAD_RX2N_B_IS_GPIO PIN_5_IS_GPIO
#endif 

#define PIN_3 PAD_RX1N_B
#define PAD_RX1N_B 216
#define GPIO_PAD_216 GPIO215
#ifndef PIN_3_IS_GPIO
#define PIN_3_IS_GPIO 0
#endif 
#ifndef PAD_RX1N_B_IS_GPIO
#define PAD_RX1N_B_IS_GPIO PIN_3_IS_GPIO
#endif 

#define PIN_4 PAD_RX1P_B
#define PAD_RX1P_B 220
#define GPIO_PAD_220 GPIO219
#ifndef PIN_4_IS_GPIO
#define PIN_4_IS_GPIO 0
#endif 
#ifndef PAD_RX1P_B_IS_GPIO
#define PAD_RX1P_B_IS_GPIO PIN_4_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_MILAN

#endif /* _MSD91G0LM_H_*/
