////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly
#ifndef _MSD91H5BN2_H_
#define _MSD91H5BN2_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PIN_8 PORT_A_PAD_RX0N
#define PORT_A_PAD_RX0N 127
#define GPIO_PAD_127 GPIO126
#ifndef PIN_8_IS_GPIO
#define PIN_8_IS_GPIO 0
#endif
#ifndef PORT_A_PAD_RX0N_IS_GPIO
#define PORT_A_PAD_RX0N_IS_GPIO PIN_8_IS_GPIO
#endif

#define PIN_6 PORT_A_PAD_RXCN
#define PORT_A_PAD_RXCN 130
#define GPIO_PAD_130 GPIO129
#ifndef PIN_6_IS_GPIO
#define PIN_6_IS_GPIO 0
#endif
#ifndef PORT_A_PAD_RXCN_IS_GPIO
#define PORT_A_PAD_RXCN_IS_GPIO PIN_6_IS_GPIO
#endif

#define PIN_9 PORT_A_PAD_RX0P
#define PORT_A_PAD_RX0P 123
#define GPIO_PAD_123 GPIO122
#ifndef PIN_9_IS_GPIO
#define PIN_9_IS_GPIO 0
#endif
#ifndef PORT_A_PAD_RX0P_IS_GPIO
#define PORT_A_PAD_RX0P_IS_GPIO PIN_9_IS_GPIO
#endif

#define PIN_7 PORT_A_PAD_RXCP
#define PORT_A_PAD_RXCP 126
#define GPIO_PAD_126 GPIO125
#ifndef PIN_7_IS_GPIO
#define PIN_7_IS_GPIO 0
#endif
#ifndef PORT_A_PAD_RXCP_IS_GPIO
#define PORT_A_PAD_RXCP_IS_GPIO PIN_7_IS_GPIO
#endif

#define PIN_13 PORT_A_PAD_RX2N
#define PORT_A_PAD_RX2N 129
#define GPIO_PAD_129 GPIO128
#ifndef PIN_13_IS_GPIO
#define PIN_13_IS_GPIO 0
#endif
#ifndef PORT_A_PAD_RX2N_IS_GPIO
#define PORT_A_PAD_RX2N_IS_GPIO PIN_13_IS_GPIO
#endif

#define PIN_11 PORT_A_PAD_RX1N
#define PORT_A_PAD_RX1N 128
#define GPIO_PAD_128 GPIO127
#ifndef PIN_11_IS_GPIO
#define PIN_11_IS_GPIO 0
#endif
#ifndef PORT_A_PAD_RX1N_IS_GPIO
#define PORT_A_PAD_RX1N_IS_GPIO PIN_11_IS_GPIO
#endif

#define PIN_14 PORT_A_PAD_RX2P
#define PORT_A_PAD_RX2P 125
#define GPIO_PAD_125 GPIO124
#ifndef PIN_14_IS_GPIO
#define PIN_14_IS_GPIO 0
#endif
#ifndef PORT_A_PAD_RX2P_IS_GPIO
#define PORT_A_PAD_RX2P_IS_GPIO PIN_14_IS_GPIO
#endif

#define PIN_12 PORT_A_PAD_RX1P
#define PORT_A_PAD_RX1P 124
#define GPIO_PAD_124 GPIO123
#ifndef PIN_12_IS_GPIO
#define PIN_12_IS_GPIO 0
#endif
#ifndef PORT_A_PAD_RX1P_IS_GPIO
#define PORT_A_PAD_RX1P_IS_GPIO PIN_12_IS_GPIO
#endif

#define PIN_18 PORT_C_PAD_RX0N
#define PORT_C_PAD_RX0N 143
#define GPIO_PAD_143 GPIO142
#ifndef PIN_18_IS_GPIO
#define PIN_18_IS_GPIO 0
#endif
#ifndef PORT_C_PAD_RX0N_IS_GPIO
#define PORT_C_PAD_RX0N_IS_GPIO PIN_18_IS_GPIO
#endif

#define PIN_16 PORT_C_PAD_RXCN
#define PORT_C_PAD_RXCN 146
#define GPIO_PAD_146 GPIO145
#ifndef PIN_16_IS_GPIO
#define PIN_16_IS_GPIO 0
#endif
#ifndef PORT_C_PAD_RXCN_IS_GPIO
#define PORT_C_PAD_RXCN_IS_GPIO PIN_16_IS_GPIO
#endif

#define PIN_19 PORT_C_PAD_RX0P
#define PORT_C_PAD_RX0P 139
#define GPIO_PAD_139 GPIO138
#ifndef PIN_19_IS_GPIO
#define PIN_19_IS_GPIO 0
#endif
#ifndef PORT_C_PAD_RX0P_IS_GPIO
#define PORT_C_PAD_RX0P_IS_GPIO PIN_19_IS_GPIO
#endif

#define PIN_17 PORT_C_PAD_RXCP
#define PORT_C_PAD_RXCP 142
#define GPIO_PAD_142 GPIO141
#ifndef PIN_17_IS_GPIO
#define PIN_17_IS_GPIO 0
#endif
#ifndef PORT_C_PAD_RXCP_IS_GPIO
#define PORT_C_PAD_RXCP_IS_GPIO PIN_17_IS_GPIO
#endif

#define PIN_23 PORT_C_PAD_RX2N
#define PORT_C_PAD_RX2N 145
#define GPIO_PAD_145 GPIO144
#ifndef PIN_23_IS_GPIO
#define PIN_23_IS_GPIO 0
#endif
#ifndef PORT_C_PAD_RX2N_IS_GPIO
#define PORT_C_PAD_RX2N_IS_GPIO PIN_23_IS_GPIO
#endif

#define PIN_21 PORT_C_PAD_RX1N
#define PORT_C_PAD_RX1N 144
#define GPIO_PAD_144 GPIO143
#ifndef PIN_21_IS_GPIO
#define PIN_21_IS_GPIO 0
#endif
#ifndef PORT_C_PAD_RX1N_IS_GPIO
#define PORT_C_PAD_RX1N_IS_GPIO PIN_21_IS_GPIO
#endif

#define PIN_24 PORT_C_PAD_RX2P
#define PORT_C_PAD_RX2P 141
#define GPIO_PAD_141 GPIO140
#ifndef PIN_24_IS_GPIO
#define PIN_24_IS_GPIO 0
#endif
#ifndef PORT_C_PAD_RX2P_IS_GPIO
#define PORT_C_PAD_RX2P_IS_GPIO PIN_24_IS_GPIO
#endif

#define PIN_22 PORT_C_PAD_RX1P
#define PORT_C_PAD_RX1P 140
#define GPIO_PAD_140 GPIO139
#ifndef PIN_22_IS_GPIO
#define PIN_22_IS_GPIO 0
#endif
#ifndef PORT_C_PAD_RX1P_IS_GPIO
#define PORT_C_PAD_RX1P_IS_GPIO PIN_22_IS_GPIO
#endif

#define PIN_27 PADA_HSYNC0
#define PADA_HSYNC0 95
#define GPIO_PAD_95 GPIO94
#ifndef PIN_27_IS_GPIO
#define PIN_27_IS_GPIO 0
#endif
#ifndef PADA_HSYNC0_IS_GPIO
#define PADA_HSYNC0_IS_GPIO PIN_27_IS_GPIO
#endif

#define PIN_28 PADA_BIN0P
#define PADA_BIN0P 107
#define GPIO_PAD_107 GPIO106
#ifndef PIN_28_IS_GPIO
#define PIN_28_IS_GPIO 0
#endif
#ifndef PADA_BIN0P_IS_GPIO
#define PADA_BIN0P_IS_GPIO PIN_28_IS_GPIO
#endif

#define PADA_BIN0M 9999
#ifndef PADA_BIN0M_IS_GPIO
#define PADA_BIN0M_IS_GPIO 0
#endif

#define PIN_29 PADA_GIN0P
#define PADA_GIN0P 103
#define GPIO_PAD_103 GPIO102
#ifndef PIN_29_IS_GPIO
#define PIN_29_IS_GPIO 0
#endif
#ifndef PADA_GIN0P_IS_GPIO
#define PADA_GIN0P_IS_GPIO PIN_29_IS_GPIO
#endif

#define PIN_30 PADA_GIN0M
#define PADA_GIN0M 105
#define GPIO_PAD_105 GPIO104
#ifndef PIN_30_IS_GPIO
#define PIN_30_IS_GPIO 0
#endif
#ifndef PADA_GIN0M_IS_GPIO
#define PADA_GIN0M_IS_GPIO PIN_30_IS_GPIO
#endif

#define PIN_31 PADA_RIN0P
#define PADA_RIN0P 99
#define GPIO_PAD_99 GPIO98
#ifndef PIN_31_IS_GPIO
#define PIN_31_IS_GPIO 0
#endif
#ifndef PADA_RIN0P_IS_GPIO
#define PADA_RIN0P_IS_GPIO PIN_31_IS_GPIO
#endif

#define PADA_RIN0M 9999
#ifndef PADA_RIN0M_IS_GPIO
#define PADA_RIN0M_IS_GPIO 0
#endif

#define PIN_32 PADA_VSYNC0
#define PADA_VSYNC0 97
#define GPIO_PAD_97 GPIO96
#ifndef PIN_32_IS_GPIO
#define PIN_32_IS_GPIO 0
#endif
#ifndef PADA_VSYNC0_IS_GPIO
#define PADA_VSYNC0_IS_GPIO PIN_32_IS_GPIO
#endif

#define PADA_HSYNC1 9999
#ifndef PADA_HSYNC1_IS_GPIO
#define PADA_HSYNC1_IS_GPIO 0
#endif

#define PADA_BIN1P 9999
#ifndef PADA_BIN1P_IS_GPIO
#define PADA_BIN1P_IS_GPIO 0
#endif

#define PADA_BIN1M 9999
#ifndef PADA_BIN1M_IS_GPIO
#define PADA_BIN1M_IS_GPIO 0
#endif

#define PADA_GIN1P 9999
#ifndef PADA_GIN1P_IS_GPIO
#define PADA_GIN1P_IS_GPIO 0
#endif

#define PADA_GIN1M 9999
#ifndef PADA_GIN1M_IS_GPIO
#define PADA_GIN1M_IS_GPIO 0
#endif

#define PADA_RIN1P 9999
#ifndef PADA_RIN1P_IS_GPIO
#define PADA_RIN1P_IS_GPIO 0
#endif

#define PADA_RIN1M 9999
#ifndef PADA_RIN1M_IS_GPIO
#define PADA_RIN1M_IS_GPIO 0
#endif

#define PADA_VSYNC1 9999
#ifndef PADA_VSYNC1_IS_GPIO
#define PADA_VSYNC1_IS_GPIO 0
#endif

#define PIN_38 PAD_LINEIN_R0
#define PAD_LINEIN_R0 112
#define GPIO_PAD_112 GPIO111
#ifndef PIN_38_IS_GPIO
#define PIN_38_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_R0_IS_GPIO
#define PAD_LINEIN_R0_IS_GPIO PIN_38_IS_GPIO
#endif

#define PIN_39 PAD_LINEIN_L0
#define PAD_LINEIN_L0 111
#define GPIO_PAD_111 GPIO110
#ifndef PIN_39_IS_GPIO
#define PIN_39_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_L0_IS_GPIO
#define PAD_LINEIN_L0_IS_GPIO PIN_39_IS_GPIO
#endif

#define PAD_LINEIN_R1 9999
#ifndef PAD_LINEIN_R1_IS_GPIO
#define PAD_LINEIN_R1_IS_GPIO 0
#endif

#define PAD_LINEIN_L1 9999
#ifndef PAD_LINEIN_L1_IS_GPIO
#define PAD_LINEIN_L1_IS_GPIO 0
#endif

#define PAD_LINEIN_R2 9999
#ifndef PAD_LINEIN_R2_IS_GPIO
#define PAD_LINEIN_R2_IS_GPIO 0
#endif

#define PAD_LINEIN_L2 9999
#ifndef PAD_LINEIN_L2_IS_GPIO
#define PAD_LINEIN_L2_IS_GPIO 0
#endif

#define PAD_LINEIN_R3 9999
#ifndef PAD_LINEIN_R3_IS_GPIO
#define PAD_LINEIN_R3_IS_GPIO 0
#endif

#define PAD_LINEIN_L3 9999
#ifndef PAD_LINEIN_L3_IS_GPIO
#define PAD_LINEIN_L3_IS_GPIO 0
#endif

#define PIN_42 PAD_LINEIN_L4
#define PAD_LINEIN_L4 119
#define GPIO_PAD_119 GPIO118
#ifndef PIN_42_IS_GPIO
#define PIN_42_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_L4_IS_GPIO
#define PAD_LINEIN_L4_IS_GPIO PIN_42_IS_GPIO
#endif

#define PIN_43 PAD_LINEIN_R4
#define PAD_LINEIN_R4 120
#define GPIO_PAD_120 GPIO119
#ifndef PIN_43_IS_GPIO
#define PIN_43_IS_GPIO 0
#endif
#ifndef PAD_LINEIN_R4_IS_GPIO
#define PAD_LINEIN_R4_IS_GPIO PIN_43_IS_GPIO
#endif

#define PAD_LINEIN_L5 9999
#ifndef PAD_LINEIN_L5_IS_GPIO
#define PAD_LINEIN_L5_IS_GPIO 0
#endif

#define PAD_LINEIN_R5 9999
#ifndef PAD_LINEIN_R5_IS_GPIO
#define PAD_LINEIN_R5_IS_GPIO 0
#endif

#define PIN_61 PAD_GPIO0
#define PAD_GPIO0 45
#define GPIO_PAD_45 GPIO44
#ifndef PIN_61_IS_GPIO
#define PIN_61_IS_GPIO 0
#endif
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO PIN_61_IS_GPIO
#endif

#define PIN_62 PAD_GPIO1
#define PAD_GPIO1 46
#define GPIO_PAD_46 GPIO45
#ifndef PIN_62_IS_GPIO
#define PIN_62_IS_GPIO 0
#endif
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO PIN_62_IS_GPIO
#endif

#define PIN_63 PAD_GPIO2
#define PAD_GPIO2 47
#define GPIO_PAD_47 GPIO46
#ifndef PIN_63_IS_GPIO
#define PIN_63_IS_GPIO 0
#endif
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO PIN_63_IS_GPIO
#endif

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif

#define PIN_64 PAD_GPIO5
#define PAD_GPIO5 50
#define GPIO_PAD_50 GPIO49
#ifndef PIN_64_IS_GPIO
#define PIN_64_IS_GPIO 0
#endif
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO PIN_64_IS_GPIO
#endif

#define PIN_65 PAD_GPIO6
#define PAD_GPIO6 51
#define GPIO_PAD_51 GPIO50
#ifndef PIN_65_IS_GPIO
#define PIN_65_IS_GPIO 0
#endif
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO PIN_65_IS_GPIO
#endif

#define PIN_66 PAD_GPIO7
#define PAD_GPIO7 52
#define GPIO_PAD_52 GPIO51
#ifndef PIN_66_IS_GPIO
#define PIN_66_IS_GPIO 0
#endif
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO PIN_66_IS_GPIO
#endif

#define PIN_67 PAD_GPIO8
#define PAD_GPIO8 53
#define GPIO_PAD_53 GPIO52
#ifndef PIN_67_IS_GPIO
#define PIN_67_IS_GPIO 0
#endif
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO PIN_67_IS_GPIO
#endif

#define PIN_68 PAD_GPIO9
#define PAD_GPIO9 54
#define GPIO_PAD_54 GPIO53
#ifndef PIN_68_IS_GPIO
#define PIN_68_IS_GPIO 0
#endif
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO PIN_68_IS_GPIO
#endif

#define PAD_B_ODD0 9999
#ifndef PAD_B_ODD0_IS_GPIO
#define PAD_B_ODD0_IS_GPIO 0
#endif

#define PAD_B_ODD1 9999
#ifndef PAD_B_ODD1_IS_GPIO
#define PAD_B_ODD1_IS_GPIO 0
#endif

#define PIN_69 PAD_B_ODD2
#define PAD_B_ODD2 42
#define GPIO_PAD_42 GPIO41
#ifndef PIN_69_IS_GPIO
#define PIN_69_IS_GPIO 0
#endif
#ifndef PAD_B_ODD2_IS_GPIO
#define PAD_B_ODD2_IS_GPIO PIN_69_IS_GPIO
#endif

#define PIN_70 PAD_B_ODD3
#define PAD_B_ODD3 41
#define GPIO_PAD_41 GPIO40
#ifndef PIN_70_IS_GPIO
#define PIN_70_IS_GPIO 0
#endif
#ifndef PAD_B_ODD3_IS_GPIO
#define PAD_B_ODD3_IS_GPIO PIN_70_IS_GPIO
#endif

#define PAD_B_ODD4 9999
#ifndef PAD_B_ODD4_IS_GPIO
#define PAD_B_ODD4_IS_GPIO 0
#endif

#define PAD_B_ODD5 9999
#ifndef PAD_B_ODD5_IS_GPIO
#define PAD_B_ODD5_IS_GPIO 0
#endif

#define PIN_71 PAD_B_ODD6
#define PAD_B_ODD6 38
#define GPIO_PAD_38 GPIO37
#ifndef PIN_71_IS_GPIO
#define PIN_71_IS_GPIO 0
#endif
#ifndef PAD_B_ODD6_IS_GPIO
#define PAD_B_ODD6_IS_GPIO PIN_71_IS_GPIO
#endif

#define PIN_72 PAD_B_ODD7
#define PAD_B_ODD7 37
#define GPIO_PAD_37 GPIO36
#ifndef PIN_72_IS_GPIO
#define PIN_72_IS_GPIO 0
#endif
#ifndef PAD_B_ODD7_IS_GPIO
#define PAD_B_ODD7_IS_GPIO PIN_72_IS_GPIO
#endif

#define PIN_73 PAD_G_ODD0
#define PAD_G_ODD0 36
#define GPIO_PAD_36 GPIO35
#ifndef PIN_73_IS_GPIO
#define PIN_73_IS_GPIO 0
#endif
#ifndef PAD_G_ODD0_IS_GPIO
#define PAD_G_ODD0_IS_GPIO PIN_73_IS_GPIO
#endif

#define PIN_74 PAD_G_ODD1
#define PAD_G_ODD1 35
#define GPIO_PAD_35 GPIO34
#ifndef PIN_74_IS_GPIO
#define PIN_74_IS_GPIO 0
#endif
#ifndef PAD_G_ODD1_IS_GPIO
#define PAD_G_ODD1_IS_GPIO PIN_74_IS_GPIO
#endif

#define PIN_75 PAD_G_ODD2
#define PAD_G_ODD2 34
#define GPIO_PAD_34 GPIO33
#ifndef PIN_75_IS_GPIO
#define PIN_75_IS_GPIO 0
#endif
#ifndef PAD_G_ODD2_IS_GPIO
#define PAD_G_ODD2_IS_GPIO PIN_75_IS_GPIO
#endif

#define PIN_76 PAD_G_ODD3
#define PAD_G_ODD3 33
#define GPIO_PAD_33 GPIO32
#ifndef PIN_76_IS_GPIO
#define PIN_76_IS_GPIO 0
#endif
#ifndef PAD_G_ODD3_IS_GPIO
#define PAD_G_ODD3_IS_GPIO PIN_76_IS_GPIO
#endif

#define PIN_80 PAD_G_ODD4
#define PAD_G_ODD4 32
#define GPIO_PAD_32 GPIO31
#ifndef PIN_80_IS_GPIO
#define PIN_80_IS_GPIO 0
#endif
#ifndef PAD_G_ODD4_IS_GPIO
#define PAD_G_ODD4_IS_GPIO PIN_80_IS_GPIO
#endif

#define PIN_81 PAD_G_ODD5
#define PAD_G_ODD5 31
#define GPIO_PAD_31 GPIO30
#ifndef PIN_81_IS_GPIO
#define PIN_81_IS_GPIO 0
#endif
#ifndef PAD_G_ODD5_IS_GPIO
#define PAD_G_ODD5_IS_GPIO PIN_81_IS_GPIO
#endif

#define PAD_G_ODD6 9999
#ifndef PAD_G_ODD6_IS_GPIO
#define PAD_G_ODD6_IS_GPIO 0
#endif

#define PAD_G_ODD7 9999
#ifndef PAD_G_ODD7_IS_GPIO
#define PAD_G_ODD7_IS_GPIO 0
#endif

#define PIN_82 PAD_R_ODD0
#define PAD_R_ODD0 28
#define GPIO_PAD_28 GPIO27
#ifndef PIN_82_IS_GPIO
#define PIN_82_IS_GPIO 0
#endif
#ifndef PAD_R_ODD0_IS_GPIO
#define PAD_R_ODD0_IS_GPIO PIN_82_IS_GPIO
#endif

#define PIN_83 PAD_R_ODD1
#define PAD_R_ODD1 27
#define GPIO_PAD_27 GPIO26
#ifndef PIN_83_IS_GPIO
#define PIN_83_IS_GPIO 0
#endif
#ifndef PAD_R_ODD1_IS_GPIO
#define PAD_R_ODD1_IS_GPIO PIN_83_IS_GPIO
#endif

#define PAD_R_ODD2 9999
#ifndef PAD_R_ODD2_IS_GPIO
#define PAD_R_ODD2_IS_GPIO 0
#endif

#define PAD_R_ODD3 9999
#ifndef PAD_R_ODD3_IS_GPIO
#define PAD_R_ODD3_IS_GPIO 0
#endif

#define PIN_85 PAD_R_ODD4
#define PAD_R_ODD4 24
#define GPIO_PAD_24 GPIO23
#ifndef PIN_85_IS_GPIO
#define PIN_85_IS_GPIO 0
#endif
#ifndef PAD_R_ODD4_IS_GPIO
#define PAD_R_ODD4_IS_GPIO PIN_85_IS_GPIO
#endif

#define PIN_86 PAD_R_ODD5
#define PAD_R_ODD5 23
#define GPIO_PAD_23 GPIO22
#ifndef PIN_86_IS_GPIO
#define PIN_86_IS_GPIO 0
#endif
#ifndef PAD_R_ODD5_IS_GPIO
#define PAD_R_ODD5_IS_GPIO PIN_86_IS_GPIO
#endif

#define PIN_87 PAD_R_ODD6
#define PAD_R_ODD6 22
#define GPIO_PAD_22 GPIO21
#ifndef PIN_87_IS_GPIO
#define PIN_87_IS_GPIO 0
#endif
#ifndef PAD_R_ODD6_IS_GPIO
#define PAD_R_ODD6_IS_GPIO PIN_87_IS_GPIO
#endif

#define PIN_88 PAD_R_ODD7
#define PAD_R_ODD7 21
#define GPIO_PAD_21 GPIO20
#ifndef PIN_88_IS_GPIO
#define PIN_88_IS_GPIO 0
#endif
#ifndef PAD_R_ODD7_IS_GPIO
#define PAD_R_ODD7_IS_GPIO PIN_88_IS_GPIO
#endif

#define PIN_89 PAD_LCK
#define PAD_LCK 20
#define GPIO_PAD_20 GPIO19
#ifndef PIN_89_IS_GPIO
#define PIN_89_IS_GPIO 0
#endif
#ifndef PAD_LCK_IS_GPIO
#define PAD_LCK_IS_GPIO PIN_89_IS_GPIO
#endif

#define PIN_90 PAD_LDE
#define PAD_LDE 19
#define GPIO_PAD_19 GPIO18
#ifndef PIN_90_IS_GPIO
#define PIN_90_IS_GPIO 0
#endif
#ifndef PAD_LDE_IS_GPIO
#define PAD_LDE_IS_GPIO PIN_90_IS_GPIO
#endif

#define PAD_LHSYNC 9999
#ifndef PAD_LHSYNC_IS_GPIO
#define PAD_LHSYNC_IS_GPIO 0
#endif

#define PAD_LVSYNC 9999
#ifndef PAD_LVSYNC_IS_GPIO
#define PAD_LVSYNC_IS_GPIO 0
#endif

#define PAD_GPIO_PM4 9999
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO 0
#endif

#define PAD_GPIO_PM5 9999
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO 0
#endif

#define PAD_GPIO_PM6 9999
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO 0
#endif

#define PAD_GPIO_PM1 9999
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO 0
#endif

#define PAD_PMGPIO 9999
#ifndef PAD_PMGPIO_IS_GPIO
#define PAD_PMGPIO_IS_GPIO 0
#endif

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif

#define PAD_GPIO17 9999
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO 0
#endif

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif

#define PIN_92 PAD_PWM3
#define PAD_PWM3 13
#define GPIO_PAD_13 GPIO12
#ifndef PIN_92_IS_GPIO
#define PIN_92_IS_GPIO 0
#endif
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO PIN_92_IS_GPIO
#endif

#define PIN_93 PAD_PWM2
#define PAD_PWM2 14
#define GPIO_PAD_14 GPIO13
#ifndef PIN_93_IS_GPIO
#define PIN_93_IS_GPIO 0
#endif
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO PIN_93_IS_GPIO
#endif

#define PAD_TCON11 9999
#ifndef PAD_TCON11_IS_GPIO
#define PAD_TCON11_IS_GPIO 0
#endif

#define PAD_TCON10 9999
#ifndef PAD_TCON10_IS_GPIO
#define PAD_TCON10_IS_GPIO 0
#endif

#define PIN_94 PAD_TCON9
#define PAD_TCON9 10
#define GPIO_PAD_10 GPIO9
#ifndef PIN_94_IS_GPIO
#define PIN_94_IS_GPIO 0
#endif
#ifndef PAD_TCON9_IS_GPIO
#define PAD_TCON9_IS_GPIO PIN_94_IS_GPIO
#endif

#define PIN_95 PAD_TCON8
#define PAD_TCON8 9
#define GPIO_PAD_9 GPIO8
#ifndef PIN_95_IS_GPIO
#define PIN_95_IS_GPIO 0
#endif
#ifndef PAD_TCON8_IS_GPIO
#define PAD_TCON8_IS_GPIO PIN_95_IS_GPIO
#endif

#define PIN_96 PAD_TCON7
#define PAD_TCON7 8
#define GPIO_PAD_8 GPIO7
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO 0
#endif
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO PIN_96_IS_GPIO
#endif

#define PIN_97 PAD_TCON6
#define PAD_TCON6 7
#define GPIO_PAD_7 GPIO6
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO 0
#endif
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO PIN_97_IS_GPIO
#endif

#define PIN_98 PAD_TCON5
#define PAD_TCON5 6
#define GPIO_PAD_6 GPIO5
#ifndef PIN_98_IS_GPIO
#define PIN_98_IS_GPIO 0
#endif
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO PIN_98_IS_GPIO
#endif

#define PIN_99 PAD_TCON4
#define PAD_TCON4 5
#define GPIO_PAD_5 GPIO4
#ifndef PIN_99_IS_GPIO
#define PIN_99_IS_GPIO 0
#endif
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO PIN_99_IS_GPIO
#endif

#define PIN_100 PAD_TCON3
#define PAD_TCON3 4
#define GPIO_PAD_4 GPIO3
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO PIN_100_IS_GPIO
#endif

#define PIN_101 PAD_TCON2
#define PAD_TCON2 3
#define GPIO_PAD_3 GPIO2
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO PIN_101_IS_GPIO
#endif

#define PIN_102 PAD_TCON1
#define PAD_TCON1 2
#define GPIO_PAD_2 GPIO1
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO PIN_102_IS_GPIO
#endif

#define PIN_103 PAD_TCON0
#define PAD_TCON0 1
#define GPIO_PAD_1 GPIO0
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO PIN_103_IS_GPIO
#endif

#define PAD_HOTPLUG_D 9999
#ifndef PAD_HOTPLUG_D_IS_GPIO
#define PAD_HOTPLUG_D_IS_GPIO 0
#endif

#define PIN_104 PAD_HOTPLUG_A
#define PAD_HOTPLUG_A 79
#define GPIO_PAD_79 GPIO78
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUG_A_IS_GPIO
#define PAD_HOTPLUG_A_IS_GPIO PIN_104_IS_GPIO
#endif

#define PIN_105 PAD_PWM1
#define PAD_PWM1 15
#define GPIO_PAD_15 GPIO14
#ifndef PIN_105_IS_GPIO
#define PIN_105_IS_GPIO 0
#endif
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_105_IS_GPIO
#endif

#define PIN_106 PAD_PWM0
#define PAD_PWM0 16
#define GPIO_PAD_16 GPIO15
#ifndef PIN_106_IS_GPIO
#define PIN_106_IS_GPIO 0
#endif
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_106_IS_GPIO
#endif

#define PIN_107 PAD_GPIO13
#define PAD_GPIO13 58
#define GPIO_PAD_58 GPIO57
#ifndef PIN_107_IS_GPIO
#define PIN_107_IS_GPIO 0
#endif
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO PIN_107_IS_GPIO
#endif

#define PIN_108 PAD_GPIO12
#define PAD_GPIO12 57
#define GPIO_PAD_57 GPIO56
#ifndef PIN_108_IS_GPIO
#define PIN_108_IS_GPIO 0
#endif
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO PIN_108_IS_GPIO
#endif

#define PIN_113 PAD_ARC
#define PAD_ARC 90
#define GPIO_PAD_90 GPIO89
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif
#ifndef PAD_ARC_IS_GPIO
#define PAD_ARC_IS_GPIO PIN_113_IS_GPIO
#endif

#define PAD_TESTPIN 9999
#ifndef PAD_TESTPIN_IS_GPIO
#define PAD_TESTPIN_IS_GPIO 0
#endif

#define PIN_116 PAD_CEC
#define PAD_CEC 72
#define GPIO_PAD_72 GPIO71
#ifndef PIN_116_IS_GPIO
#define PIN_116_IS_GPIO 0
#endif
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO PIN_116_IS_GPIO
#endif

#define PIN_118 PAD_INT
#define PAD_INT 65
#define GPIO_PAD_65 GPIO64
#ifndef PIN_118_IS_GPIO
#define PIN_118_IS_GPIO 0
#endif
#ifndef PAD_INT_IS_GPIO
#define PAD_INT_IS_GPIO PIN_118_IS_GPIO
#endif

#define PIN_125 PAD_SAR0
#define PAD_SAR0 76
#define GPIO_PAD_76 GPIO75
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_125_IS_GPIO
#endif

#define PIN_126 PAD_SAR1
#define PAD_SAR1 75
#define GPIO_PAD_75 GPIO74
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_126_IS_GPIO
#endif

#define PIN_127 PAD_SAR2
#define PAD_SAR2 74
#define GPIO_PAD_74 GPIO73
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO PIN_127_IS_GPIO
#endif

#define PIN_128 PAD_SAR3
#define PAD_SAR3 73
#define GPIO_PAD_73 GPIO72
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO PIN_128_IS_GPIO
#endif

#define PIN_129 PAD_HOTPLUGA_HDMI20_5V
#define PAD_HOTPLUGA_HDMI20_5V 91
#define GPIO_PAD_91 GPIO90
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGA_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGA_HDMI20_5V_IS_GPIO PIN_129_IS_GPIO
#endif

#define PAD_HOTPLUG_C 9999
#ifndef PAD_HOTPLUG_C_IS_GPIO
#define PAD_HOTPLUG_C_IS_GPIO 0
#endif

#define PAD_HOTPLUGD_HDMI20_5V 9999
#ifndef PAD_HOTPLUGD_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGD_HDMI20_5V_IS_GPIO 0
#endif

#define PAD_DDCDD_CLK 9999
#ifndef PAD_DDCDD_CLK_IS_GPIO
#define PAD_DDCDD_CLK_IS_GPIO 0
#endif

#define PAD_DDCDD_DAT 9999
#ifndef PAD_DDCDD_DAT_IS_GPIO
#define PAD_DDCDD_DAT_IS_GPIO 0
#endif

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif

#define PIN_136 PAD_DDCDC_DAT
#define PAD_DDCDC_DAT 84
#define GPIO_PAD_84 GPIO83
#ifndef PIN_136_IS_GPIO
#define PIN_136_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_DAT_IS_GPIO
#define PAD_DDCDC_DAT_IS_GPIO PIN_136_IS_GPIO
#endif

#define PIN_137 PAD_DDCDC_CLK
#define PAD_DDCDC_CLK 83
#define GPIO_PAD_83 GPIO82
#ifndef PIN_137_IS_GPIO
#define PIN_137_IS_GPIO 0
#endif
#ifndef PAD_DDCDC_CLK_IS_GPIO
#define PAD_DDCDC_CLK_IS_GPIO PIN_137_IS_GPIO
#endif

#define PIN_138 PAD_DDCDA_DAT
#define PAD_DDCDA_DAT 78
#define GPIO_PAD_78 GPIO77
#ifndef PIN_138_IS_GPIO
#define PIN_138_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_DAT_IS_GPIO
#define PAD_DDCDA_DAT_IS_GPIO PIN_138_IS_GPIO
#endif

#define PIN_139 PAD_DDCDA_CLK
#define PAD_DDCDA_CLK 77
#define GPIO_PAD_77 GPIO76
#ifndef PIN_139_IS_GPIO
#define PIN_139_IS_GPIO 0
#endif
#ifndef PAD_DDCDA_CLK_IS_GPIO
#define PAD_DDCDA_CLK_IS_GPIO PIN_139_IS_GPIO
#endif

#define PIN_140 PAD_MHL_DET
#define PAD_MHL_DET 89
#define GPIO_PAD_89 GPIO88
#ifndef PIN_140_IS_GPIO
#define PIN_140_IS_GPIO 0
#endif
#ifndef PAD_MHL_DET_IS_GPIO
#define PAD_MHL_DET_IS_GPIO PIN_140_IS_GPIO
#endif

#define PIN_141 PAD_DDCDB_DAT
#define PAD_DDCDB_DAT 81
#define GPIO_PAD_81 GPIO80
#ifndef PIN_141_IS_GPIO
#define PIN_141_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_DAT_IS_GPIO
#define PAD_DDCDB_DAT_IS_GPIO PIN_141_IS_GPIO
#endif

#define PIN_142 PAD_DDCDB_CLK
#define PAD_DDCDB_CLK 80
#define GPIO_PAD_80 GPIO79
#ifndef PIN_142_IS_GPIO
#define PIN_142_IS_GPIO 0
#endif
#ifndef PAD_DDCDB_CLK_IS_GPIO
#define PAD_DDCDB_CLK_IS_GPIO PIN_142_IS_GPIO
#endif

#define PIN_143 PAD_HOTPLUG_B
#define PAD_HOTPLUG_B 82
#define GPIO_PAD_82 GPIO81
#ifndef PIN_143_IS_GPIO
#define PIN_143_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUG_B_IS_GPIO
#define PAD_HOTPLUG_B_IS_GPIO PIN_143_IS_GPIO
#endif

#define PIN_144 PAD_HOTPLUGB_HDMI20_5V
#define PAD_HOTPLUGB_HDMI20_5V 92
#define GPIO_PAD_92 GPIO91
#ifndef PIN_144_IS_GPIO
#define PIN_144_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGB_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGB_HDMI20_5V_IS_GPIO PIN_144_IS_GPIO
#endif

#define PIN_145 PAD_HOTPLUGC_HDMI20_5V
#define PAD_HOTPLUGC_HDMI20_5V 93
#define GPIO_PAD_93 GPIO92
#ifndef PIN_145_IS_GPIO
#define PIN_145_IS_GPIO 0
#endif
#ifndef PAD_HOTPLUGC_HDMI20_5V_IS_GPIO
#define PAD_HOTPLUGC_HDMI20_5V_IS_GPIO PIN_145_IS_GPIO
#endif

#define PIN_148 PAD_ECBSS_P1
#define PAD_ECBSS_P1 156
#define GPIO_PAD_156 GPIO155
#ifndef PIN_148_IS_GPIO
#define PIN_148_IS_GPIO 0
#endif
#ifndef PAD_ECBSS_P1_IS_GPIO
#define PAD_ECBSS_P1_IS_GPIO PIN_148_IS_GPIO
#endif

#define PIN_149 PAD_ECBSS_P0
#define PAD_ECBSS_P0 155
#define GPIO_PAD_155 GPIO154
#ifndef PIN_149_IS_GPIO
#define PIN_149_IS_GPIO 0
#endif
#ifndef PAD_ECBSS_P0_IS_GPIO
#define PAD_ECBSS_P0_IS_GPIO PIN_149_IS_GPIO
#endif

#define PORT_D_PAD_RXCN 9999
#ifndef PORT_D_PAD_RXCN_IS_GPIO
#define PORT_D_PAD_RXCN_IS_GPIO 0
#endif

#define PORT_D_PAD_RX0N 9999
#ifndef PORT_D_PAD_RX0N_IS_GPIO
#define PORT_D_PAD_RX0N_IS_GPIO 0
#endif

#define PORT_D_PAD_RXCP 9999
#ifndef PORT_D_PAD_RXCP_IS_GPIO
#define PORT_D_PAD_RXCP_IS_GPIO 0
#endif

#define PORT_D_PAD_RX0P 9999
#ifndef PORT_D_PAD_RX0P_IS_GPIO
#define PORT_D_PAD_RX0P_IS_GPIO 0
#endif

#define PORT_D_PAD_RX1N 9999
#ifndef PORT_D_PAD_RX1N_IS_GPIO
#define PORT_D_PAD_RX1N_IS_GPIO 0
#endif

#define PORT_D_PAD_RX2N 9999
#ifndef PORT_D_PAD_RX2N_IS_GPIO
#define PORT_D_PAD_RX2N_IS_GPIO 0
#endif

#define PORT_D_PAD_RX1P 9999
#ifndef PORT_D_PAD_RX1P_IS_GPIO
#define PORT_D_PAD_RX1P_IS_GPIO 0
#endif

#define PORT_D_PAD_RX2P 9999
#ifndef PORT_D_PAD_RX2P_IS_GPIO
#define PORT_D_PAD_RX2P_IS_GPIO 0
#endif

#define PIN_153 PORT_B_PAD_RXCN
#define PORT_B_PAD_RXCN 138
#define GPIO_PAD_138 GPIO137
#ifndef PIN_153_IS_GPIO
#define PIN_153_IS_GPIO 0
#endif
#ifndef PORT_B_PAD_RXCN_IS_GPIO
#define PORT_B_PAD_RXCN_IS_GPIO PIN_153_IS_GPIO
#endif

#define PIN_155 PORT_B_PAD_RX0N
#define PORT_B_PAD_RX0N 135
#define GPIO_PAD_135 GPIO134
#ifndef PIN_155_IS_GPIO
#define PIN_155_IS_GPIO 0
#endif
#ifndef PORT_B_PAD_RX0N_IS_GPIO
#define PORT_B_PAD_RX0N_IS_GPIO PIN_155_IS_GPIO
#endif

#define PIN_154 PORT_B_PAD_RXCP
#define PORT_B_PAD_RXCP 134
#define GPIO_PAD_134 GPIO133
#ifndef PIN_154_IS_GPIO
#define PIN_154_IS_GPIO 0
#endif
#ifndef PORT_B_PAD_RXCP_IS_GPIO
#define PORT_B_PAD_RXCP_IS_GPIO PIN_154_IS_GPIO
#endif

#define PIN_156 PORT_B_PAD_RX0P
#define PORT_B_PAD_RX0P 131
#define GPIO_PAD_131 GPIO130
#ifndef PIN_156_IS_GPIO
#define PIN_156_IS_GPIO 0
#endif
#ifndef PORT_B_PAD_RX0P_IS_GPIO
#define PORT_B_PAD_RX0P_IS_GPIO PIN_156_IS_GPIO
#endif

#define PIN_1 PORT_B_PAD_RX1N
#define PORT_B_PAD_RX1N 136
#define GPIO_PAD_136 GPIO135
#ifndef PIN_1_IS_GPIO
#define PIN_1_IS_GPIO 0
#endif
#ifndef PORT_B_PAD_RX1N_IS_GPIO
#define PORT_B_PAD_RX1N_IS_GPIO PIN_1_IS_GPIO
#endif

#define PIN_3 PORT_B_PAD_RX2N
#define PORT_B_PAD_RX2N 137
#define GPIO_PAD_137 GPIO136
#ifndef PIN_3_IS_GPIO
#define PIN_3_IS_GPIO 0
#endif
#ifndef PORT_B_PAD_RX2N_IS_GPIO
#define PORT_B_PAD_RX2N_IS_GPIO PIN_3_IS_GPIO
#endif

#define PIN_2 PORT_B_PAD_RX1P
#define PORT_B_PAD_RX1P 132
#define GPIO_PAD_132 GPIO131
#ifndef PIN_2_IS_GPIO
#define PIN_2_IS_GPIO 0
#endif
#ifndef PORT_B_PAD_RX1P_IS_GPIO
#define PORT_B_PAD_RX1P_IS_GPIO PIN_2_IS_GPIO
#endif

#define PIN_4 PORT_B_PAD_RX2P
#define PORT_B_PAD_RX2P 133
#define GPIO_PAD_133 GPIO132
#ifndef PIN_4_IS_GPIO
#define PIN_4_IS_GPIO 0
#endif
#ifndef PORT_B_PAD_RX2P_IS_GPIO
#define PORT_B_PAD_RX2P_IS_GPIO PIN_4_IS_GPIO
#endif


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1
#define CHIP_HAS_UART2_MODE2       1
#define CHIP_HAS_UART2_MODE3       1
#define CHIP_HAS_RGB_A             1
#define CHIP_HAS_RGB_B             1
#define CHIP_HAS_RGB_C             1
#define CHIP_HAS_HDMI_A            1
#define CHIP_HAS_HDMI_B            1
#define CHIP_HAS_HDMI_C            1
#define CHIP_HAS_SPI_CZ1           1
#define CHIP_HAS_SPI_CZ2           0
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1
#define CHIP_HAS_DDCR2             1
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1
#define CHIP_HAS_ET_MODE0_RMII     1
#define CHIP_HAS_ET_MODE1_MII      1
#define CHIP_HAS_ET_MODE1_RMII     1
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_MAYA

#endif /* _MSD91H5BN2_H_*/
