////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2017 09:17:51]
/////////////////////////////////////////////////////////////////////////////



//////////////////////////////////////////////////////
// Window List (Position)

WINDOWPOSDATA _MP_TBLSEG _GUI_WindowPositionList_Zui_Channel_Info[] =
{
    // HWND_MAINFRAME
    {
        HWND_MAINFRAME, HWND_CHINFO_POP_SECOND_SRC_ICON,
        { 1, 0, 958, 175 },
    },

    // HWND_CHINFO_TRANSPARENT_BG
    {
        HWND_MAINFRAME, HWND_CHINFO_TRANSPARENT_BG,
        { 2, 2, 956, 174 },
    },

    // HWND_CHINFO_ROOT_PANE
    {
        HWND_MAINFRAME, HWND_CHINFO_POP_SECOND_SRC_ICON,
        { 2, 2, 956, 174 },
    },

    // HWND_CHINFO_EXT_PANE
    {
        HWND_CHINFO_ROOT_PANE, HWND_CHINFO_EXT_SUBTITLE_ICON,
        { 2, 11, 956, 165 },
    },

    // HWND_CHINFO_EXT_TOP_BG
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_TOP_BG,
        { 953, 33, 5, 30 },
    },

    // HWND_CHINFO_EXT_TOP_BG_L
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_TOP_BG_L,
        { 2, 33, 951, 30 },
    },

    // HWND_CHINFO_EXT_CONTENT_BG_GREEN
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CONTENT_BG_GREEN,
        { 2, 63, 956, 28 },
    },

    // HWND_CHINFO_EXT_CONTENT_SIMPLE_BG
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CONTENT_SIMPLE_BG,
        { 2, 88, 956, 46 },
    },

    // HWND_CHINFO_EXT_CONTENT_EXTENSION_BG
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_UPDOWN_ARROW_ICON,
        { 2, 133, 956, 43 },
    },

    // HWND_CHINFO_EXT_CONTENT_TEXT
    {
        HWND_CHINFO_EXT_CONTENT_EXTENSION_BG, HWND_CHINFO_EXT_CONTENT_TEXT,
        { 33, 133, 892, 43 },
    },

    // HWND_CHINFO_EXT_UPDOWN_ARROW_ICON
    {
        HWND_CHINFO_EXT_CONTENT_EXTENSION_BG, HWND_CHINFO_EXT_UPDOWN_ARROW_ICON,
        { 929, 134, 29, 42 },
    },

    // HWND_CHINFO_EXT_RARROW_ICON
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_RARROW_ICON,
        { 929, 63, 29, 25 },
    },

    // HWND_CHINFO_EXT_LARROW_ICON
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_LARROW_ICON,
        { 2, 63, 28, 25 },
    },

    // HWND_CHINFO_EXT_CH_NUMBER_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CH_NUMBER_TEXT,
        { 35, 31, 70, 30 },
    },

    // HWND_CHINFO_EXT_CH_NAME_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CH_NAME_TEXT,
        { 120, 31, 129, 31 },
    },

    // HWND_CHINFO_EXT_TOP_TIME_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_TOP_TIME_TEXT,
        { 397, 31, 133, 30 },
    },

    // HWND_CHINFO_EXT_TOP_DATE_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_TOP_DATE_TEXT,
        { 253, 31, 133, 30 },
    },

    // HWND_CHINFO_EXT_TIME_START_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_TIME_START_TEXT,
        { 33, 62, 105, 25 },
    },

    // HWND_CHINFO_EXT_TIME_END_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_TIME_END_TEXT,
        { 140, 62, 105, 25 },
    },

    // HWND_CHINFO_EXT_NAME_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_NAME_TEXT,
        { 260, 62, 438, 28 },
    },

    // HWND_CHINFO_EXT_GENRE_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_GENRE_TEXT,
        { 713, 62, 154, 28 },
    },

    // HWND_CHINFO_EXT_AGE_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_AGE_TEXT,
        { 867, 60, 49, 28 },
    },

    // HWND_CHINFO_EXT_VIDEO_TYPE_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_VIDEO_TYPE_TEXT,
        { 28, 91, 142, 21 },
    },

    // HWND_CHINFO_EXT_VIDEO_RES_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_VIDEO_RES_TEXT,
        { 82, 91, 143, 21 },
    },

    // HWND_CHINFO_EXT_CH_COLOR_SYS_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CH_COLOR_SYS_TEXT,
        { 184, 91, 142, 22 },
    },

    // HWND_CHINFO_EXT_CH_SOUND_SYS_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CH_SOUND_SYS_TEXT,
        { 333, 91, 142, 22 },
    },

    // HWND_CHINFO_EXT_CH_INPUT_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CH_INPUT_TEXT,
        { 483, 91, 142, 22 },
    },

    // HWND_CHINFO_EXT_CH_SDHD_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CH_SDHD_TEXT,
        { 633, 91, 142, 22 },
    },

    // HWND_CHINFO_EXT_CH_MTS_TYPE_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CH_MTS_TYPE_TEXT,
        { 775, 91, 156, 22 },
    },

    // HWND_CHINFO_EXT_CH_AUDIO_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_CH_AUDIO_TEXT,
        { 34, 111, 142, 22 },
    },

    // HWND_CHINFO_EXT_MHEG_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_MHEG_TEXT,
        { 184, 111, 142, 22 },
    },

    // HWND_CHINFO_EXT_NARRATION_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_NARRATION_TEXT,
        { 333, 111, 142, 22 },
    },

    // HWND_CHINFO_EXT_SUBTITLE_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_SUBTITLE_TEXT,
        { 483, 111, 142, 22 },
    },

    // HWND_CHINFO_EXT_AUDIO_LANG_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_AUDIO_LANG_TEXT,
        { 633, 111, 142, 22 },
    },

    // HWND_CHINFO_EXT_TELETEXT_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_TELETEXT_TEXT,
        { 775, 111, 142, 22 },
    },

    // HWND_CHINFO_EXT_FIRST_SRC_ICON
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_FIRST_SRC_ICON,
        { 7, 38, 22, 15 },
    },

    // HWND_CHINFO_EXT_S2_SATLITENAME_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_S2_SATLITENAME_TEXT,
        { 453, 31, 212, 30 },
    },

    // HWND_CHINFO_EXT_S2_PREQ_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_S2_PREQ_TEXT,
        { 670, 31, 250, 30 },
    },

    // HWND_CHINFO_EXT_S2_SYMBOL_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_S2_SYMBOL_TEXT,
        { 399, 67, 142, 21 },
    },

    // HWND_CHINFO_EXT_S2_SIGNAL_STRENGTH_TEXT
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_S2_SIGNAL_STRENGTH_TEXT,
        { 633, 67, 142, 21 },
    },

    // HWND_CHINFO_EXT_SUBTITLE_ICON
    {
        HWND_CHINFO_EXT_PANE, HWND_CHINFO_EXT_SUBTITLE_ICON,
        { 433, 111, 50, 22 },
    },

    // HWND_CHINFO_PIP_SRC_INFO_AREA
    {
        HWND_CHINFO_ROOT_PANE, HWND_CHINFO_PIP_SRC2_VIDEO_RES_TEXT,
        { 2, 154, 956, 22 },
    },

    // HWND_CHINFO_PIP_SRC1_INFO_AREA
    {
        HWND_CHINFO_PIP_SRC_INFO_AREA, HWND_CHINFO_PIP_SRC1_VIDEO_RES_TEXT,
        { 2, 154, 956, 22 },
    },

    // HWND_CHINFO_PIP_SRC1_INFO_BG
    {
        HWND_CHINFO_PIP_SRC1_INFO_AREA, HWND_CHINFO_PIP_SRC1_INFO_BG,
        { 2, 154, 956, 22 },
    },

    // HWND_CHINFO_PIP_SRC1_ICON
    {
        HWND_CHINFO_PIP_SRC1_INFO_AREA, HWND_CHINFO_PIP_SRC1_ICON,
        { 5, 158, 22, 15 },
    },

    // HWND_CHINFO_PIP_SRC1_SOURCE_TYPE_TEXT
    {
        HWND_CHINFO_PIP_SRC1_INFO_AREA, HWND_CHINFO_PIP_SRC1_SOURCE_TYPE_TEXT,
        { 33, 155, 132, 21 },
    },

    // HWND_CHINFO_PIP_SRC1_VIDEO_RES_TEXT
    {
        HWND_CHINFO_PIP_SRC1_INFO_AREA, HWND_CHINFO_PIP_SRC1_VIDEO_RES_TEXT,
        { 173, 155, 132, 21 },
    },

    // HWND_CHINFO_PIP_SRC2_INFO_AREA
    {
        HWND_CHINFO_PIP_SRC_INFO_AREA, HWND_CHINFO_PIP_SRC2_VIDEO_RES_TEXT,
        { 2, 154, 956, 22 },
    },

    // HWND_CHINFO_PIP_SRC2_INFO_BG
    {
        HWND_CHINFO_PIP_SRC2_INFO_AREA, HWND_CHINFO_PIP_SRC2_INFO_BG,
        { 2, 154, 956, 22 },
    },

    // HWND_CHINFO_PIP_SRC2_ICON
    {
        HWND_CHINFO_PIP_SRC2_INFO_AREA, HWND_CHINFO_PIP_SRC2_ICON,
        { 5, 158, 22, 15 },
    },

    // HWND_CHINFO_PIP_SRC2_SOURCE_TYPE_TEXT
    {
        HWND_CHINFO_PIP_SRC2_INFO_AREA, HWND_CHINFO_PIP_SRC2_SOURCE_TYPE_TEXT,
        { 33, 155, 132, 21 },
    },

    // HWND_CHINFO_PIP_SRC2_VIDEO_RES_TEXT
    {
        HWND_CHINFO_PIP_SRC2_INFO_AREA, HWND_CHINFO_PIP_SRC2_VIDEO_RES_TEXT,
        { 173, 155, 132, 21 },
    },

    // HWND_CHINFO_POP_PANE
    {
        HWND_CHINFO_ROOT_PANE, HWND_CHINFO_POP_SECOND_SRC_ICON,
        { 2, 75, 956, 101 },
    },

    // HWND_CHINFO_POP_LEFT_AREA
    {
        HWND_CHINFO_POP_PANE, HWND_CHINFO_POP_FIRST_SRC_ICON,
        { 2, 21, 480, 155 },
    },

    // HWND_CHINFO_POP_LEFT_TV_INFO
    {
        HWND_CHINFO_POP_LEFT_AREA, HWND_CHINFO_POP_LEFT_CH_AUDIO_TEXT,
        { 2, 21, 477, 155 },
    },

    // HWND_CHINFO_POP_LEFT_TV_BG
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_TV_BG,
        { 2, 21, 477, 30 },
    },

    // HWND_CHINFO_POP_LEFT_TV_BG_DOWN
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_TV_BG_DOWN,
        { 2, 51, 477, 125 },
    },

    // HWND_CHINFO_POP_LEFT_TV_GREEN_BG
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_TV_GREEN_BG,
        { 2, 51, 477, 56 },
    },

    // HWND_CHINFO_POP_LEFT_CH_NUMBER_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_CH_NUMBER_TEXT,
        { 33, 21, 132, 30 },
    },

    // HWND_CHINFO_POP_LEFT_CH_NAME_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_CH_NAME_TEXT,
        { 173, 21, 132, 30 },
    },

    // HWND_CHINFO_POP_LEFT_TIME_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_TIME_TEXT,
        { 306, 21, 93, 30 },
    },

    // HWND_CHINFO_POP_LEFT_LARROW_ICON
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_LARROW_ICON,
        { 2, 63, 28, 25 },
    },

    // HWND_CHINFO_POP_LEFT_RARROW_ICON
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_RARROW_ICON,
        { 451, 63, 28, 25 },
    },

    // HWND_CHINFO_POP_LEFT_TIME_START_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_TIME_START_TEXT,
        { 33, 80, 66, 28 },
    },

    // HWND_CHINFO_POP_LEFT_TIME_END_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_TIME_END_TEXT,
        { 99, 80, 66, 28 },
    },

    // HWND_CHINFO_POP_LEFT_NAME_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_NAME_TEXT,
        { 33, 51, 154, 28 },
    },

    // HWND_CHINFO_POP_LEFT_GENRE_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_GENRE_TEXT,
        { 216, 80, 73, 28 },
    },

    // HWND_CHINFO_POP_LEFT_AGE_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_AGE_TEXT,
        { 283, 80, 44, 28 },
    },

    // HWND_CHINFO_POP_LEFT_TV_VIDEO_RES_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_TV_VIDEO_RES_TEXT,
        { 216, 110, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_CH_COLOR_SYS_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_CH_COLOR_SYS_TEXT,
        { 33, 132, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_CH_SOUND_SYS_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_CH_SOUND_SYS_TEXT,
        { 139, 132, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_CH_INPUT_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_CH_INPUT_TEXT,
        { 243, 132, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_CH_SDHD_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_CH_SDHD_TEXT,
        { 348, 132, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_CH_MTS_TYPE_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_CH_MTS_TYPE_TEXT,
        { 33, 109, 175, 23 },
    },

    // HWND_CHINFO_POP_LEFT_TELETEXT_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_TELETEXT_TEXT,
        { 348, 110, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_AUDIO_LANG_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_AUDIO_LANG_TEXT,
        { 348, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_SUBTITLE_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_SUBTITLE_TEXT,
        { 243, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_NARRATION_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_NARRATION_TEXT,
        { 243, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_MHEG_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_MHEG_TEXT,
        { 139, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_CH_AUDIO_TEXT
    {
        HWND_CHINFO_POP_LEFT_TV_INFO, HWND_CHINFO_POP_LEFT_CH_AUDIO_TEXT,
        { 33, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_LEFT_SRC_INFO
    {
        HWND_CHINFO_POP_LEFT_AREA, HWND_CHINFO_POP_LEFT_VIDEO_RES_TEXT,
        { 2, 71, 477, 105 },
    },

    // HWND_CHINFO_POP_LEFT_SRC_BG
    {
        HWND_CHINFO_POP_LEFT_SRC_INFO, HWND_CHINFO_POP_LEFT_SRC_BG,
        { 2, 21, 477, 30 },
    },

    // HWND_CHINFO_POP_LEFT_SRC_BG_LINE
    {
        HWND_CHINFO_POP_LEFT_SRC_INFO, HWND_CHINFO_POP_LEFT_SRC_BG_LINE,
        { 2, 51, 477, 125 },
    },

    // HWND_CHINFO_POP_LEFT_SOURCE_TYPE_TEXT
    {
        HWND_CHINFO_POP_LEFT_SRC_INFO, HWND_CHINFO_POP_LEFT_SOURCE_TYPE_TEXT,
        { 35, 109, 62, 21 },
    },

    // HWND_CHINFO_POP_LEFT_VIDEO_RES_TEXT
    {
        HWND_CHINFO_POP_LEFT_SRC_INFO, HWND_CHINFO_POP_LEFT_VIDEO_RES_TEXT,
        { 139, 109, 132, 21 },
    },

    // HWND_CHINFO_POP_FIRST_SRC_ICON
    {
        HWND_CHINFO_POP_LEFT_AREA, HWND_CHINFO_POP_FIRST_SRC_ICON,
        { 5, 28, 22, 15 },
    },

    // HWND_CHINFO_POP_RIGHT_AREA
    {
        HWND_CHINFO_POP_PANE, HWND_CHINFO_POP_SECOND_SRC_ICON,
        { 478, 75, 478, 101 },
    },

    // HWND_CHINFO_POP_RIGHT_TV_INFO
    {
        HWND_CHINFO_POP_RIGHT_AREA, HWND_CHINFO_POP_RIGHT_CH_AUDIO_TEXT,
        { 478, 21, 478, 155 },
    },

    // HWND_CHINFO_POP_RIGHT_TV_BG
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_TV_BG,
        { 478, 21, 478, 30 },
    },

    // HWND_CHINFO_POP_RIGHT_TV_BG_DOWN
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_TV_BG_DOWN,
        { 478, 51, 478, 125 },
    },

    // HWND_CHINFO_POP_RIGHT_TV_GREEN_BG
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_TV_GREEN_BG,
        { 478, 51, 478, 56 },
    },

    // HWND_CHINFO_POP_RIGHT_CH_NUMBER_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_CH_NUMBER_TEXT,
        { 513, 21, 132, 30 },
    },

    // HWND_CHINFO_POP_RIGHT_CH_NAME_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_CH_NAME_TEXT,
        { 653, 21, 132, 30 },
    },

    // HWND_CHINFO_POP_RIGHT_TIME_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_TIME_TEXT,
        { 793, 21, 132, 30 },
    },

    // HWND_CHINFO_POP_RIGHT_LARROW_ICON
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_LARROW_ICON,
        { 480, 63, 28, 25 },
    },

    // HWND_CHINFO_POP_RIGHT_RARROW_ICON
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_RARROW_ICON,
        { 929, 63, 29, 27 },
    },

    // HWND_CHINFO_POP_RIGHT_TIME_START_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_TIME_START_TEXT,
        { 514, 80, 66, 28 },
    },

    // HWND_CHINFO_POP_RIGHT_TIME_END_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_TIME_END_TEXT,
        { 579, 80, 66, 28 },
    },

    // HWND_CHINFO_POP_RIGHT_NAME_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_NAME_TEXT,
        { 514, 51, 154, 28 },
    },

    // HWND_CHINFO_POP_RIGHT_GENRE_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_GENRE_TEXT,
        { 696, 80, 73, 28 },
    },

    // HWND_CHINFO_POP_RIGHT_AGE_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_AGE_TEXT,
        { 763, 80, 44, 28 },
    },

    // HWND_CHINFO_POP_RIGHT_TV_VIDEO_RES_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_TV_VIDEO_RES_TEXT,
        { 696, 109, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_CH_COLOR_SYS_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_CH_COLOR_SYS_TEXT,
        { 514, 132, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_CH_SOUND_SYS_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_CH_SOUND_SYS_TEXT,
        { 619, 132, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_CH_INPUT_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_CH_INPUT_TEXT,
        { 724, 132, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_CH_SDHD_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_CH_SDHD_TEXT,
        { 829, 132, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_CH_MTS_TYPE_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_CH_MTS_TYPE_TEXT,
        { 514, 109, 175, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_TELETEXT_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_TELETEXT_TEXT,
        { 828, 109, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_AUDIO_LANG_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_AUDIO_LANG_TEXT,
        { 829, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_SUBTITLE_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_SUBTITLE_TEXT,
        { 723, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_NARRATION_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_NARRATION_TEXT,
        { 724, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_MHEG_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_MHEG_TEXT,
        { 619, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_CH_AUDIO_TEXT
    {
        HWND_CHINFO_POP_RIGHT_TV_INFO, HWND_CHINFO_POP_RIGHT_CH_AUDIO_TEXT,
        { 514, 153, 62, 23 },
    },

    // HWND_CHINFO_POP_RIGHT_SRC_INFO
    {
        HWND_CHINFO_POP_RIGHT_AREA, HWND_CHINFO_POP_RIGHT_VIDEO_RES_TEXT,
        { 478, 71, 478, 105 },
    },

    // HWND_CHINFO_POP_RIGHT_SRC_BG
    {
        HWND_CHINFO_POP_RIGHT_SRC_INFO, HWND_CHINFO_POP_RIGHT_SRC_BG,
        { 478, 21, 478, 30 },
    },

    // HWND_CHINFO_POP_RIGHT_SRC_BG_LINE
    {
        HWND_CHINFO_POP_RIGHT_SRC_INFO, HWND_CHINFO_POP_RIGHT_SRC_BG_LINE,
        { 478, 51, 478, 125 },
    },

    // HWND_CHINFO_POP_RIGHT_SOURCE_TYPE_TEXT
    {
        HWND_CHINFO_POP_RIGHT_SRC_INFO, HWND_CHINFO_POP_RIGHT_SOURCE_TYPE_TEXT,
        { 515, 109, 62, 21 },
    },

    // HWND_CHINFO_POP_RIGHT_VIDEO_RES_TEXT
    {
        HWND_CHINFO_POP_RIGHT_SRC_INFO, HWND_CHINFO_POP_RIGHT_VIDEO_RES_TEXT,
        { 619, 109, 132, 21 },
    },

    // HWND_CHINFO_POP_SECOND_SRC_ICON
    {
        HWND_CHINFO_POP_RIGHT_AREA, HWND_CHINFO_POP_SECOND_SRC_ICON,
        { 486, 28, 22, 15 },
    },

};
