////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2017 09:17:51]
/////////////////////////////////////////////////////////////////////////////



//////////////////////////////////////////////////////
// Window List (Position)

WINDOWPOSDATA _MP_TBLSEG _GUI_WindowPositionList_Zui_Message_Box[] =
{
    // HWND_MAINFRAME
    {
        HWND_MAINFRAME, HWND_EWS_FRAME_WASPADA_SCROLL_BAR_1,
        { 695, 29, 236, 196 },
    },

    // HWND_MSGBOX_COMMON
    {
        HWND_MAINFRAME, HWND_MSGBOX_USB_LIST_ITEM3_TEXT,
        { 695, 29, 236, 196 },
    },

    // HWND_MSGBOX_COMMON_BG
    {
        HWND_MSGBOX_COMMON, HWND_MSGBOX_COMMON_BG_R,
        { 695, 29, 236, 196 },
    },

    // HWND_MSGBOX_COMMON_BG_TOP
    {
        HWND_MSGBOX_COMMON_BG, HWND_MSGBOX_COMMON_BG_TOP,
        { 695, 29, 236, 34 },
    },

    // HWND_MSGBOX_COMMON_NEW_BG_L
    {
        HWND_MSGBOX_COMMON_BG, HWND_MSGBOX_COMMON_NEW_BG_L,
        { 695, 63, 4, 162 },
    },

    // HWND_MSGBOX_COMMON_NEW_BG_C
    {
        HWND_MSGBOX_COMMON_BG, HWND_MSGBOX_COMMON_NEW_BG_C,
        { 699, 63, 227, 162 },
    },

    // HWND_MSGBOX_COMMON_NEW_BG_R
    {
        HWND_MSGBOX_COMMON_BG, HWND_MSGBOX_COMMON_NEW_BG_R,
        { 926, 63, 4, 162 },
    },

    // HWND_MSGBOX_COMMON_BG_L
    {
        HWND_MSGBOX_COMMON_BG, HWND_MSGBOX_COMMON_BG_L,
        { 695, 63, 4, 162 },
    },

    // HWND_MSGBOX_COMMON_BG_C
    {
        HWND_MSGBOX_COMMON_BG, HWND_MSGBOX_COMMON_BG_C,
        { 699, 63, 227, 162 },
    },

    // HWND_MSGBOX_COMMON_BG_R
    {
        HWND_MSGBOX_COMMON_BG, HWND_MSGBOX_COMMON_BG_R,
        { 926, 63, 4, 162 },
    },

    // HWND_MSGBOX_COMMON_TITLE
    {
        HWND_MSGBOX_COMMON, HWND_MSGBOX_COMMON_TITLE,
        { 695, 29, 236, 33 },
    },

    // HWND_MSGBOX_TEXT_PANE
    {
        HWND_MSGBOX_COMMON, HWND_MSGBOX_COMMON_TEXT2,
        { 697, 90, 231, 43 },
    },

    // HWND_MSGBOX_COMMON_TEXT1
    {
        HWND_MSGBOX_TEXT_PANE, HWND_MSGBOX_COMMON_TEXT1,
        { 697, 90, 231, 21 },
    },

    // HWND_MSGBOX_COMMON_TEXT2
    {
        HWND_MSGBOX_TEXT_PANE, HWND_MSGBOX_COMMON_TEXT2,
        { 697, 112, 231, 21 },
    },

    // HWND_MSGBOX_PASSWORD_PANE
    {
        HWND_MSGBOX_COMMON, HWND_MSGBOX_PASSWORD_INPUT_4,
        { 735, 134, 154, 31 },
    },

    // HWND_MSGBOX_PASSWORD_INPUT_1
    {
        HWND_MSGBOX_PASSWORD_PANE, HWND_MSGBOX_PASSWORD_INPUT_1,
        { 756, 134, 23, 23 },
    },

    // HWND_MSGBOX_PASSWORD_INPUT_2
    {
        HWND_MSGBOX_PASSWORD_PANE, HWND_MSGBOX_PASSWORD_INPUT_2,
        { 786, 134, 23, 23 },
    },

    // HWND_MSGBOX_PASSWORD_INPUT_3
    {
        HWND_MSGBOX_PASSWORD_PANE, HWND_MSGBOX_PASSWORD_INPUT_3,
        { 815, 134, 23, 23 },
    },

    // HWND_MSGBOX_PASSWORD_INPUT_4
    {
        HWND_MSGBOX_PASSWORD_PANE, HWND_MSGBOX_PASSWORD_INPUT_4,
        { 845, 134, 23, 23 },
    },

    // HWND_MSGBOX_PASSWORD_PRESSED_PANE
    {
        HWND_MSGBOX_COMMON, HWND_MSGBOX_PASSWORD_PRESSED_4,
        { 735, 134, 154, 31 },
    },

    // HWND_MSGBOX_PASSWORD_PRESSED_1
    {
        HWND_MSGBOX_PASSWORD_PRESSED_PANE, HWND_MSGBOX_PASSWORD_PRESSED_1,
        { 761, 139, 14, 14 },
    },

    // HWND_MSGBOX_PASSWORD_PRESSED_2
    {
        HWND_MSGBOX_PASSWORD_PRESSED_PANE, HWND_MSGBOX_PASSWORD_PRESSED_2,
        { 791, 139, 14, 14 },
    },

    // HWND_MSGBOX_PASSWORD_PRESSED_3
    {
        HWND_MSGBOX_PASSWORD_PRESSED_PANE, HWND_MSGBOX_PASSWORD_PRESSED_3,
        { 820, 139, 14, 14 },
    },

    // HWND_MSGBOX_PASSWORD_PRESSED_4
    {
        HWND_MSGBOX_PASSWORD_PRESSED_PANE, HWND_MSGBOX_PASSWORD_PRESSED_4,
        { 850, 139, 14, 14 },
    },

    // HWND_MSGBOX_COMMON_BTN_PANE
    {
        HWND_MSGBOX_COMMON, HWND_MSGBOX_COMMON_MSG_OK,
        { 697, 203, 231, 21 },
    },

    // HWND_MSGBOX_COMMON_BTN_CLEAR
    {
        HWND_MSGBOX_COMMON_BTN_PANE, HWND_MSGBOX_COMMON_BTN_CLEAR_TEXT,
        { 697, 203, 119, 21 },
    },

    // HWND_MSGBOX_COMMON_BTN_CLEAR_LEFT_ARROW
    {
        HWND_MSGBOX_COMMON_BTN_CLEAR, HWND_MSGBOX_COMMON_BTN_CLEAR_LEFT_ARROW,
        { 695, 203, 15, 21 },
    },

    // HWND_MSGBOX_COMMON_BTN_CLEAR_TEXT
    {
        HWND_MSGBOX_COMMON_BTN_CLEAR, HWND_MSGBOX_COMMON_BTN_CLEAR_TEXT,
        { 710, 203, 71, 21 },
    },

    // HWND_MSGBOX_COMMON_BTN_OK
    {
        HWND_MSGBOX_COMMON_BTN_PANE, HWND_MSGBOX_COMMON_BTN_CANCEL_TEXT,
        { 809, 203, 119, 21 },
    },

    // HWND_MSGBOX_COMMON_BTN_CANCEL_RIGHT_ARROW
    {
        HWND_MSGBOX_COMMON_BTN_OK, HWND_MSGBOX_COMMON_BTN_CANCEL_RIGHT_ARROW,
        { 915, 203, 15, 21 },
    },

    // HWND_MSGBOX_COMMON_BTN_CANCEL_TEXT
    {
        HWND_MSGBOX_COMMON_BTN_OK, HWND_MSGBOX_COMMON_BTN_CANCEL_TEXT,
        { 843, 203, 71, 21 },
    },

    // HWND_MSGBOX_COMMON_MSG_OK
    {
        HWND_MSGBOX_COMMON_BTN_PANE, HWND_MSGBOX_COMMON_MSG_OK,
        { 697, 203, 119, 21 },
    },

    // HWND_MSGBOX_USB_LIST_PANE
    {
        HWND_MSGBOX_COMMON, HWND_MSGBOX_USB_LIST_ITEM3_TEXT,
        { 695, 63, 236, 137 },
    },

    // HWND_MSGBOX_USB_LIST_ITEM0
    {
        HWND_MSGBOX_USB_LIST_PANE, HWND_MSGBOX_USB_LIST_ITEM0_TEXT,
        { 695, 63, 236, 32 },
    },

    // HWND_MSGBOX_USB_LIST_ITEM0_TEXT
    {
        HWND_MSGBOX_USB_LIST_ITEM0, HWND_MSGBOX_USB_LIST_ITEM0_TEXT,
        { 704, 63, 217, 32 },
    },

    // HWND_MSGBOX_USB_LIST_ITEM1
    {
        HWND_MSGBOX_USB_LIST_PANE, HWND_MSGBOX_USB_LIST_ITEM1_TEXT,
        { 695, 99, 236, 32 },
    },

    // HWND_MSGBOX_USB_LIST_ITEM1_TEXT
    {
        HWND_MSGBOX_USB_LIST_ITEM1, HWND_MSGBOX_USB_LIST_ITEM1_TEXT,
        { 704, 99, 217, 32 },
    },

    // HWND_MSGBOX_USB_LIST_ITEM2
    {
        HWND_MSGBOX_USB_LIST_PANE, HWND_MSGBOX_USB_LIST_ITEM2_TEXT,
        { 695, 134, 236, 32 },
    },

    // HWND_MSGBOX_USB_LIST_ITEM2_TEXT
    {
        HWND_MSGBOX_USB_LIST_ITEM2, HWND_MSGBOX_USB_LIST_ITEM2_TEXT,
        { 704, 134, 217, 32 },
    },

    // HWND_MSGBOX_USB_LIST_ITEM3
    {
        HWND_MSGBOX_USB_LIST_PANE, HWND_MSGBOX_USB_LIST_ITEM3_TEXT,
        { 695, 169, 236, 32 },
    },

    // HWND_MSGBOX_USB_LIST_ITEM3_TEXT
    {
        HWND_MSGBOX_USB_LIST_ITEM3, HWND_MSGBOX_USB_LIST_ITEM3_TEXT,
        { 704, 169, 217, 32 },
    },

    // HWND_EWS_FRAME
    {
        HWND_MAINFRAME, HWND_REMARK_DESCRIPTION,
        { 157, 42, 650, 475 },
    },

    // HWND_DISASTER_SYMBOL
    {
        HWND_EWS_FRAME, HWND_DISASTER_SYMBOL,
        { 198, 91, 84, 84 },
    },

    // HWND_AUTHOR_SYMBOL
    {
        HWND_EWS_FRAME, HWND_AUTHOR_SYMBOL,
        { 682, 91, 84, 84 },
    },

    // HWND_DISASTER_LOCATION_STATUS_TXT
    {
        HWND_EWS_FRAME, HWND_DISASTER_LOCATION_STATUS_TXT,
        { 366, 76, 260, 37 },
    },

    // HWND_LOCATION_OF_DISASTER
    {
        HWND_EWS_FRAME, HWND_LOCATION_OF_DISASTER,
        { 366, 128, 260, 37 },
    },

    // HWND_DISASTER_TYPE
    {
        HWND_EWS_FRAME, HWND_TYPE_CONTENT,
        { 224, 210, 498, 30 },
    },

    // HWND_TYPE_TITLE
    {
        HWND_DISASTER_TYPE, HWND_TYPE_TITLE,
        { 229, 210, 112, 30 },
    },

    // HWND_TYPE_CONTENT
    {
        HWND_DISASTER_TYPE, HWND_TYPE_CONTENT,
        { 364, 210, 355, 30 },
    },

    // HWND_DISASTER_DATE_AND_TIME
    {
        HWND_EWS_FRAME, HWND_DATE_CONTENT,
        { 225, 246, 498, 30 },
    },

    // HWND_DATE_TITLE
    {
        HWND_DISASTER_DATE_AND_TIME, HWND_DATE_TITLE,
        { 229, 246, 112, 30 },
    },

    // HWND_DATE_CONTENT
    {
        HWND_DISASTER_DATE_AND_TIME, HWND_DATE_CONTENT,
        { 364, 246, 355, 30 },
    },

    // HWND_DISASTER_LONGITUDE
    {
        HWND_EWS_FRAME, HWND_LONGITUDE_CONTENT,
        { 225, 281, 498, 30 },
    },

    // HWND_LONGITUDE_TITLE
    {
        HWND_DISASTER_LONGITUDE, HWND_LONGITUDE_TITLE,
        { 229, 281, 112, 30 },
    },

    // HWND_LONGITUDE_CONTENT
    {
        HWND_DISASTER_LONGITUDE, HWND_LONGITUDE_CONTENT,
        { 364, 281, 355, 30 },
    },

    // HWND_DISASTER_CHARACTER
    {
        HWND_EWS_FRAME, HWND_CHARACTER_CONTENT,
        { 225, 316, 498, 30 },
    },

    // HWND_CHARACTER_TITLE
    {
        HWND_DISASTER_CHARACTER, HWND_CHARACTER_TITLE,
        { 229, 316, 112, 30 },
    },

    // HWND_CHARACTER_CONTENT
    {
        HWND_DISASTER_CHARACTER, HWND_CHARACTER_CONTENT,
        { 364, 316, 355, 30 },
    },

    // HWND_REMARK
    {
        HWND_EWS_FRAME, HWND_REMARK_CONTENT,
        { 225, 351, 498, 30 },
    },

    // HWND_REMARK_TITLE
    {
        HWND_REMARK, HWND_REMARK_TITLE,
        { 229, 351, 112, 30 },
    },

    // HWND_REMARK_CONTENT
    {
        HWND_REMARK, HWND_REMARK_CONTENT,
        { 364, 351, 355, 30 },
    },

    // HWND_REMARK_DESCRIPTION
    {
        HWND_EWS_FRAME, HWND_REMARK_DESCRIPTION,
        { 224, 383, 498, 99 },
    },

    // HWND_EWS_FRAME_WASPADA
    {
        HWND_MAINFRAME, HWND_EWS_FRAME_WASPADA_SCROLL_BAR_1,
        { 157, 246, 650, 271 },
    },

    // HWND_DISASTER_SYMBOL2
    {
        HWND_EWS_FRAME_WASPADA, HWND_DISASTER_SYMBOL2,
        { 198, 268, 84, 84 },
    },

    // HWND_AUTHOR_SYMBOL2
    {
        HWND_EWS_FRAME_WASPADA, HWND_AUTHOR_SYMBOL2,
        { 682, 268, 84, 84 },
    },

    // HWND_DISASTER_LOCATION_STATUS_TXT2
    {
        HWND_EWS_FRAME_WASPADA, HWND_DISASTER_LOCATION_STATUS_TXT2,
        { 286, 296, 260, 37 },
    },

    // HWND_LOCATION_OF_DISASTER2
    {
        HWND_EWS_FRAME_WASPADA, HWND_LOCATION_OF_DISASTER2,
        { 539, 292, 143, 37 },
    },

    // HWND_REMARK_DESCRIPTION2
    {
        HWND_EWS_FRAME_WASPADA, HWND_REMARK_DESCRIPTION2,
        { 224, 383, 498, 99 },
    },

    // HWND_EWS_FRAME_WASPADA_SCROLL_BG
    {
        HWND_EWS_FRAME_WASPADA, HWND_EWS_FRAME_WASPADA_SCROLL_BAR_1,
        { 726, 383, 16, 99 },
    },

    // HWND_EWS_FRAME_WASPADA_SCROLL_BG_1
    {
        HWND_EWS_FRAME_WASPADA_SCROLL_BG, HWND_EWS_FRAME_WASPADA_SCROLL_BG_1,
        { 728, 385, 13, 96 },
    },

    // HWND_EWS_FRAME_WASPADA_SCROLL_BAR
    {
        HWND_EWS_FRAME_WASPADA_SCROLL_BG, HWND_EWS_FRAME_WASPADA_SCROLL_BAR_1,
        { 728, 393, 12, 18 },
    },

    // HWND_EWS_FRAME_WASPADA_SCROLL_BAR_1
    {
        HWND_EWS_FRAME_WASPADA_SCROLL_BAR, HWND_EWS_FRAME_WASPADA_SCROLL_BAR_1,
        { 730, 395, 9, 16 },
    },

};
