////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2010 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (''MStar Confidential Information'') by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////
// This file is automatically generated by SkinTool [Version:0.2.3][Build:Jun 14 2017 09:17:51]
/////////////////////////////////////////////////////////////////////////////



//////////////////////////////////////////////////////
// Window List (Position)

WINDOWPOSDATA _MP_TBLSEG _GUI_WindowPositionList_Zui_Channel_Info_Atsc[] =
{
    // HWND_MAINFRAME
    {
        HWND_MAINFRAME, HWND_CHINFO_DIRECT_TUNE_PANEL_TEXT,
        { 0, 0, 960, 539 },
    },

    // HWND_CHINFO_TRANSPARENT
    {
        HWND_MAINFRAME, HWND_CHINFO_TRANSPARENT,
        { 0, 0, 960, 539 },
    },

    // HWND_CHINFO_BTM_EXT_PANE
    {
        HWND_MAINFRAME, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_BLUE,
        { 0, 394, 960, 145 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_BG
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_BTM_EXT_PANE_EXTENTION_BG,
        { 0, 394, 960, 145 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_TITLE_C
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_TITLE_C,
        { 0, 394, 524, 30 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_TITLE_R
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_TITLE_R,
        { 578, 394, 4, 30 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_GREEN_BG
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_GREEN_BG,
        { 0, 425, 960, 28 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_SIMPLE_BG
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_SIMPLE_BG,
        { 0, 451, 960, 46 },
    },

    // HWND_CHINFO_BTM_EXT_PANE_EXTENTION_BG
    {
        HWND_CHINFO_BTM_EXT_PANE_BG, HWND_CHINFO_BTM_EXT_PANE_EXTENTION_BG,
        { 0, 496, 960, 43 },
    },

    // HWND_CHINFO_PROG_NUM_TEXT
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_PROG_NUM_TEXT,
        { 11, 394, 105, 30 },
    },

    // HWND_CHINFO_PROG_NAME_TEXT
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_PROG_NAME_TEXT,
        { 119, 394, 129, 30 },
    },

    // HWND_CHINFO_CONTENT_1ST_ROW_CC_INFO
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_1ST_ROW_CC_INFO,
        { 73, 454, 208, 22 },
    },

    // HWND_CHINFO_CONTENT_2ND_ROW_RESOLUTION
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_2ND_ROW_RESOLUTION,
        { 676, 454, 245, 22 },
    },

    // HWND_CHINFO_CONTENT_1ST_ROW_CC_ICON
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_1ST_ROW_CC_ICON,
        { 32, 454, 35, 17 },
    },

    // HWND_CHINFO_CONTENT_2ND_ROW_VID_RES_ICON
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_2ND_ROW_VID_RES_ICON,
        { 331, 454, 142, 20 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_TIME_TEXT
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_3RD_ROW_TIME_TEXT,
        { 250, 394, 328, 30 },
    },

    // HWND_CHINFO_CONTENT_1ST_ROW_EVENT_INFO
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_1ST_ROW_EVENT_INFO,
        { 258, 425, 438, 25 },
    },

    // HWND_CHINFO_CONTENT_2ND_ROW_SCRAMBLE_STATUS
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_2ND_ROW_SCRAMBLE_STATUS,
        { 32, 474, 639, 22 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR
    {
        HWND_CHINFO_BTM_EXT_PANE, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_BLUE,
        { 676, 474, 245, 22 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_TEXT
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_TEXT,
        { 794, 474, 56, 22 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_RED
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_RED,
        { 676, 483, 29, 5 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_YELLOW
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_YELLOW,
        { 705, 483, 29, 5 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_GREEN
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_GREEN,
        { 735, 483, 29, 5 },
    },

    // HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_BLUE
    {
        HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR, HWND_CHINFO_CONTENT_3RD_ROW_SIGNAL_BAR_BLUE,
        { 764, 483, 29, 5 },
    },

    // HWND_CHINFO_ETT_BG
    {
        HWND_MAINFRAME, HWND_CHINFO_ETT_TEXT,
        { 0, 496, 960, 43 },
    },

    // HWND_CHINFO_ETT_TEXT
    {
        HWND_CHINFO_ETT_BG, HWND_CHINFO_ETT_TEXT,
        { 31, 496, 892, 43 },
    },

    // HWND_CHINFO_BANNER
    {
        HWND_MAINFRAME, HWND_CHINFO_BANNER_PROG_SCRAMBLE_INFO,
        { 778, 18, 180, 70 },
    },

    // HWND_CHINFO_BANNER_BG
    {
        HWND_CHINFO_BANNER, HWND_CHINFO_BANNER_BG,
        { 778, 18, 180, 70 },
    },

    // HWND_CHINFO_BANNER_PROG_NUM
    {
        HWND_CHINFO_BANNER, HWND_CHINFO_BANNER_PROG_NUM,
        { 778, 18, 180, 28 },
    },

    // HWND_CHINFO_BANNER_PROG_NAME
    {
        HWND_CHINFO_BANNER, HWND_CHINFO_BANNER_PROG_NAME,
        { 778, 44, 180, 28 },
    },

    // HWND_CHINFO_BANNER_PROG_SCRAMBLE_INFO
    {
        HWND_CHINFO_BANNER, HWND_CHINFO_BANNER_PROG_SCRAMBLE_INFO,
        { 778, 71, 180, 16 },
    },

    // HWND_CHINFO_DIRECT_TUNE_PANEL
    {
        HWND_MAINFRAME, HWND_CHINFO_DIRECT_TUNE_PANEL_TEXT,
        { 11, 14, 153, 40 },
    },

    // HWND_CHINFO_DIRECT_TUNE_PANEL_BG
    {
        HWND_CHINFO_DIRECT_TUNE_PANEL, HWND_CHINFO_DIRECT_TUNE_PANEL_BG,
        { 15, 14, 42, 40 },
    },

    // HWND_CHINFO_DIRECT_TUNE_PANEL_TEXT
    {
        HWND_CHINFO_DIRECT_TUNE_PANEL, HWND_CHINFO_DIRECT_TUNE_PANEL_TEXT,
        { 59, 14, 102, 40 },
    },

};
